<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Results – Beyond Asphalt</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-discussion.html" rel="next">
<link href="./03-methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7f6aace0ffd29614ddc7d54ad3d34ca0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-ee26e69d2bffe44000086689866e607f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-7f6aace0ffd29614ddc7d54ad3d34ca0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-results.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Beyond Asphalt</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sabernaseralavi-60/2026_International-Roughness-Index-Prediction-Using-the-LTPP/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Beyond-Asphalt.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abstract</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-related-work.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Related Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data and Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-limitations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Limitations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About the Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#dataset-summary" id="toc-dataset-summary" class="nav-link active" data-scroll-target="#dataset-summary"><span class="header-section-number">4.1</span> Dataset summary</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">4.2</span> Model comparison</a></li>
  <li><a href="#robustness-and-sensitivity-checks" id="toc-robustness-and-sensitivity-checks" class="nav-link" data-scroll-target="#robustness-and-sensitivity-checks"><span class="header-section-number">4.3</span> Robustness and sensitivity checks</a></li>
  <li><a href="#what-drives-iri-shap-feature-attribution" id="toc-what-drives-iri-shap-feature-attribution" class="nav-link" data-scroll-target="#what-drives-iri-shap-feature-attribution"><span class="header-section-number">4.4</span> What drives IRI: SHAP feature attribution</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/sabernaseralavi-60/2026_International-Roughness-Index-Prediction-Using-the-LTPP/edit/master/04-results.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sabernaseralavi-60/2026_International-Roughness-Index-Prediction-Using-the-LTPP/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-results" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Results</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="dataset-summary" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="dataset-summary"><span class="header-section-number">4.1</span> Dataset summary</h2>
<p><a href="#tbl-dataset-summary" class="quarto-xref">Table&nbsp;<span>4.1</span></a> summarizes the two assembled panels.</p>
<div class="cell" data-execution_count="1">
<div id="tbl-dataset-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Summary of the assembled flexible and rigid LTPP IRI datasets (IRI min/max in tables/dataset_summary.csv).
</figcaption>
<div aria-describedby="tbl-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Dataset</th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">Sections</th>
<th data-quarto-table-cell-role="th">States</th>
<th data-quarto-table-cell-role="th">IRI mean</th>
<th data-quarto-table-cell-role="th">IRI sd</th>
<th data-quarto-table-cell-role="th">Age mean (yr)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible (GPS-1/2)</td>
<td>1552</td>
<td>208</td>
<td>55</td>
<td>1.56</td>
<td>0.66</td>
<td>10.13</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rigid (GPS-3/4/5/6/9)</td>
<td>1693</td>
<td>179</td>
<td>46</td>
<td>1.74</td>
<td>0.66</td>
<td>13.12</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Both panels span a comparable range of in-service roughness (<a href="#fig-iri-dist" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>), with the familiar right-skew of a well-maintained highway network: most sections cluster between 1 and 2 m/km, with a thin tail of rougher outliers that any predictive model has to work hard to capture.</p>
<div id="fig-iri-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iri-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/iri_distribution.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iri-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Distribution of IRI by pavement family.
</figcaption>
</figure>
</div>
<p>Age and IRI show the expected — and expectedly noisy — relationship (<a href="#fig-iri-age" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>): both families roughen somewhat with age, but the relationship is weak on its own, which is precisely the motivation for a multivariate model that can weigh age against structure, climate, and accumulated distress simultaneously rather than reading it off a single scatterplot.</p>
<div id="fig-iri-age" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iri-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/iri_vs_age.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iri-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: IRI versus pavement age at the time of survey, by family.
</figcaption>
</figure>
</div>
</section>
<section id="model-comparison" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">4.2</span> Model comparison</h2>
<p>For every pavement family we fit three variants: the primary <strong>structural</strong> model (distress, structure, climate, and imputed traffic/LTE — no lagged IRI), a <strong>traffic+LTE-ablated</strong> structural model (the same rows and split, minus those two imputed variables, isolating their marginal contribution), and an <strong>operational</strong> model that adds the section’s own previous IRI reading. <a href="#tbl-master" class="quarto-xref">Table&nbsp;<span>4.2</span></a> reports held-out LightGBM performance across all of them; <a href="#tbl-flex-metrics" class="quarto-xref">Table&nbsp;<span>4.3</span></a> and <a href="#tbl-rigid-metrics" class="quarto-xref">Table&nbsp;<span>4.4</span></a> give the full four-model comparison (linear, random forest, Optuna-tuned ANN, Optuna-tuned LightGBM) for the primary structural variant.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-master" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-master-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.2: LightGBM held-out R² across every pavement family and model variant (full N/RMSE detail in tables/master_lightgbm_comparison.csv).
</figcaption>
<div aria-describedby="tbl-master-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pavement family</th>
<th data-quarto-table-cell-role="th">Variant</th>
<th data-quarto-table-cell-role="th">R2 (held-out)</th>
<th data-quarto-table-cell-role="th">CV R2 mean</th>
<th data-quarto-table-cell-role="th">CV R2 std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible (GPS-1/2)</td>
<td>Structural (full)</td>
<td>0.414</td>
<td>0.227</td>
<td>0.113</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Flexible (GPS-1/2)</td>
<td>No traffic/LTE</td>
<td>0.395</td>
<td>0.210</td>
<td>0.107</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Flexible (GPS-1/2)</td>
<td>Operational (lag)</td>
<td>0.698</td>
<td>0.542</td>
<td>0.095</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Rigid, pooled</td>
<td>Structural (full)</td>
<td>0.220</td>
<td>0.188</td>
<td>0.099</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Rigid, pooled</td>
<td>No traffic/LTE</td>
<td>0.203</td>
<td>0.166</td>
<td>0.087</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Rigid, pooled</td>
<td>Operational (lag)</td>
<td>0.391</td>
<td>0.570</td>
<td>0.125</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Rigid, JPCP only</td>
<td>Structural (full)</td>
<td>-0.294</td>
<td>0.182</td>
<td>0.048</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Rigid, JPCP only</td>
<td>No traffic/LTE</td>
<td>-0.331</td>
<td>0.185</td>
<td>0.052</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Rigid, JPCP only</td>
<td>Operational (lag)</td>
<td>0.431</td>
<td>0.574</td>
<td>0.117</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Rigid, CRCP only</td>
<td>Structural (full)</td>
<td>0.226</td>
<td>0.066</td>
<td>0.246</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Rigid, CRCP only</td>
<td>No traffic/LTE</td>
<td>0.244</td>
<td>0.082</td>
<td>0.290</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Rigid, CRCP only</td>
<td>Operational (lag)</td>
<td>0.268</td>
<td>0.540</td>
<td>0.256</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="3">
<div id="tbl-flex-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-flex-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.3: Structural model comparison — flexible (asphalt) pavements (MAE in tables/flexible_structural_model_metrics.csv).
</figcaption>
<div aria-describedby="tbl-flex-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">R2</th>
<th data-quarto-table-cell-role="th">RMSE</th>
<th data-quarto-table-cell-role="th">Time (s)</th>
<th data-quarto-table-cell-role="th">vs RF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Linear (M-E style)</td>
<td>0.196</td>
<td>0.579</td>
<td>3.054</td>
<td>1.071</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Random Forest</td>
<td>0.324</td>
<td>0.531</td>
<td>3.272</td>
<td>1.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>ANN (tuned)</td>
<td>0.107</td>
<td>0.610</td>
<td>1.769</td>
<td>1.850</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>LightGBM (tuned)</td>
<td>0.414</td>
<td>0.495</td>
<td>0.785</td>
<td>4.170</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>XGBoost (Optuna-tuned)</td>
<td>0.382</td>
<td>0.508</td>
<td>0.756</td>
<td>4.325</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>CatBoost (Optuna-tuned)</td>
<td>0.395</td>
<td>0.502</td>
<td>1.010</td>
<td>3.241</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="4">
<div id="tbl-rigid-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rigid-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.4: Structural model comparison — rigid pavements, pooled JPCP+JRCP+CRCP (MAE in tables/rigid_structural_model_metrics.csv).
</figcaption>
<div aria-describedby="tbl-rigid-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">R2</th>
<th data-quarto-table-cell-role="th">RMSE</th>
<th data-quarto-table-cell-role="th">Time (s)</th>
<th data-quarto-table-cell-role="th">vs RF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Linear (M-E style)</td>
<td>0.139</td>
<td>0.640</td>
<td>2.086</td>
<td>1.067</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Random Forest</td>
<td>0.195</td>
<td>0.619</td>
<td>2.226</td>
<td>1.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>ANN (tuned)</td>
<td>0.009</td>
<td>0.687</td>
<td>4.681</td>
<td>0.476</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>LightGBM (tuned)</td>
<td>0.220</td>
<td>0.609</td>
<td>1.531</td>
<td>1.454</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>XGBoost (Optuna-tuned)</td>
<td>0.210</td>
<td>0.613</td>
<td>1.685</td>
<td>1.321</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>CatBoost (Optuna-tuned)</td>
<td>0.163</td>
<td>0.631</td>
<td>1.975</td>
<td>1.127</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Four findings emerge from <a href="#tbl-master" class="quarto-xref">Table&nbsp;<span>4.2</span></a>. First, <strong>Optuna tuning and MICE-style traffic/LTE imputation meaningfully lift the structural models</strong> relative to an untuned configuration with traffic/LTE excluded: flexible-pavement <span class="math inline">\(R^2\)</span> rises from 0.333 to 0.414, and pooled rigid from 0.254 to 0.220 — the rigid figure is a rare case where systematic tuning <em>did not</em> help (discussed below). Second, <strong>removing traffic and LTE costs a small but consistent amount of accuracy everywhere</strong> (flexible: 0.414 → 0.395; pooled rigid: 0.220 → 0.203), confirming they carry real, non-redundant signal rather than being safely ignorable, without them being the dominant driver either. Third, <strong>the operational (lagged-IRI) variant is dramatically more accurate everywhere</strong> (<span class="math inline">\(R^2=0.698\)</span> flexible, <span class="math inline">\(0.391\)</span> pooled rigid), which is expected — IRI is strongly autocorrelated within a section — and is reported as a distinct, clearly-labeled model rather than folded into the “structural” headline number, since the two answer different engineering questions (see <a href="03-methods.html" class="quarto-xref"><span>Chapter 3</span></a>). Fourth, <strong>pooling JPCP/JRCP and CRCP into one rigid model outperforms splitting them</strong>: the JPCP/JRCP-only structural submodel is actually <em>worse than predicting the mean</em> (<span class="math inline">\(R^2=-0.294\)</span>, <span class="math inline">\(n=118\)</span> sections), and the CRCP-only submodel, while positive (<span class="math inline">\(R^2=0.226\)</span>), carries enormous cross-validation variance (<span class="math inline">\(\pm0.246\)</span>) from having only 61 sections to work with. Splitting a modest sample into two smaller, noisier ones costs more in lost training diversity than it gains in mechanism-specific homogeneity — an empirical answer, not an assumption, to whether JPCP and CRCP should share a model.</p>
<p>The rigid-pavement ANN is the clearest illustration of a tree ensemble’s advantage in this small-section-count regime: even after a 40-trial Optuna search over architecture, L2 regularization, and learning rate, it manages only <span class="math inline">\(R^2=0.009\)</span> (pooled) to <span class="math inline">\(R^2=-1.23\)</span> (CRCP-only) on the structural task — worse, in the CRCP case, than predicting the sample mean — while LightGBM’s built-in leaf-wise regularization stays positive across every rigid variant. Because the ANN is tuned against the same group-aware cross-validation objective as LightGBM, its weaker performance reflects a genuine bias-variance trade-off in a few-hundred-section regime rather than inadequate tuning of the baseline.</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why the ensemble wins on speed, not just accuracy
</div>
</div>
<div class="callout-body-container callout-body">
<p>LightGBM’s histogram-based split-finding and leaf-wise tree growth make it substantially cheaper to train than either the ANN (repeated gradient-descent epochs) or the random forest (hundreds of fully-grown, un-pruned trees). Across every family and variant in <a href="#tbl-master" class="quarto-xref">Table&nbsp;<span>4.2</span></a>, tuned LightGBM trains 1.7<span class="math inline">\(\times\)</span> to 9<span class="math inline">\(\times\)</span> faster than the random forest baseline. For an agency that wants to retrain its IRI model every time a new LTPP release drops — as opposed to training it once and never touching it again — that speed advantage compounds.</p>
</div>
</div>
</section>
<section id="robustness-and-sensitivity-checks" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="robustness-and-sensitivity-checks"><span class="header-section-number">4.3</span> Robustness and sensitivity checks</h2>
<p>Five further checks accompany the headline structural model, addressing gradient-boosting implementation choice, split methodology, age provenance, imputation method, and candidate feature additions in turn.</p>
<p><strong>Gradient-boosting implementation.</strong> <a href="#tbl-gbm-compare" class="quarto-xref">Table&nbsp;<span>4.5</span></a> compares LightGBM against XGBoost <span class="citation" data-cites="chen2016xgboost"><a href="references.html#ref-chen2016xgboost" role="doc-biblioref">[1]</a></span> and CatBoost <span class="citation" data-cites="prokhorenkova2018catboost"><a href="references.html#ref-prokhorenkova2018catboost" role="doc-biblioref">[2]</a></span>, each independently tuned with a 25-trial Optuna search against the same group-aware cross-validation objective as the headline model.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-gbm-compare" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gbm-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.5: Structural-model R² by gradient-boosting implementation.
</figcaption>
<div aria-describedby="tbl-gbm-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pavement family</th>
<th data-quarto-table-cell-role="th">LightGBM R2</th>
<th data-quarto-table-cell-role="th">XGBoost R2</th>
<th data-quarto-table-cell-role="th">CatBoost R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible</td>
<td>0.414</td>
<td>0.382</td>
<td>0.395</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rigid, pooled</td>
<td>0.220</td>
<td>0.210</td>
<td>0.163</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Rigid, JPCP/JRCP only</td>
<td>-0.294</td>
<td>-0.325</td>
<td>-0.264</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Rigid, CRCP only</td>
<td>0.226</td>
<td>0.170</td>
<td>0.095</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>LightGBM is the best- or near-best-performing implementation in three of four cases, and is within 0.03-0.06 <span class="math inline">\(R^2\)</span> of the best alternative in the fourth (JPCP/JRCP-only, where CatBoost edges ahead in an already low-accuracy regime). The choice among modern gradient-boosting implementations does not change any of this study’s conclusions.</p>
<p><strong>Split methodology, and why its effect varies by family.</strong> <a href="#tbl-leakage" class="quarto-xref">Table&nbsp;<span>4.6</span></a> reports, for each family, the same Optuna-tuned hyperparameters evaluated under a naive row-level split and under the group-aware split used throughout this study, isolating the contribution of splitting strategy alone from any confound with hyperparameter selection.</p>
<div class="cell" data-execution_count="6">
<div id="tbl-leakage" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-leakage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.6: Naive-split vs.&nbsp;group-aware-split R², same tuned hyperparameters.
</figcaption>
<div aria-describedby="tbl-leakage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pavement family</th>
<th data-quarto-table-cell-role="th">Naive-split R2</th>
<th data-quarto-table-cell-role="th">Group-aware R2</th>
<th data-quarto-table-cell-role="th">Inflation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible</td>
<td>0.417</td>
<td>0.414</td>
<td>0.003</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rigid, pooled</td>
<td>0.440</td>
<td>0.220</td>
<td>0.220</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Rigid, JPCP/JRCP only</td>
<td>0.355</td>
<td>-0.294</td>
<td>0.649</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Rigid, CRCP only</td>
<td>0.365</td>
<td>0.226</td>
<td>0.139</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The inflation from a naive split is not constant: it is negligible for flexible pavements (0.417 vs.&nbsp;0.414) but substantial for rigid pavements, and largest of all for the JPCP/JRCP-only submodel (0.355 vs.&nbsp;-0.294, an inflation of 0.649 <span class="math inline">\(R^2\)</span>) — precisely the configuration whose structural feature set explains the least genuine variance. This is consistent with a specific mechanism rather than a generic warning: when a naive split allows repeated visits of the same section into both training and test data, the model can recover a section’s persistent, unmeasured characteristics from its training-set visits and apply that section-specific signature to held-out visits of the <em>same</em> section. That recovery is most profitable, and therefore produces the largest apparent accuracy gain, exactly where the measured covariates explain the smallest share of true variance, since more of the outcome is then attributable to persistent section identity that only a naive split allows to leak through. A well-tuned model evaluated on a well-explained outcome (flexible pavements) has comparatively little unexplained section-specific variance left for a naive split to exploit; a model facing a poorly-explained outcome (JPCP/JRCP structural roughness) has a great deal, and a naive split rewards memorizing it. This is a more specific and testable claim than the coarser observation that an early, less-regularized configuration of the flexible-pavement model showed a large naive-vs-grouped gap (0.52 vs. 0.33): leakage-driven inflation should scale with the fraction of outcome variance the structural features fail to explain, a pattern <a href="#tbl-leakage" class="quarto-xref">Table&nbsp;<span>4.6</span></a> confirms across four independently-tuned models spanning a wide range of explanatory power.</p>
<p><strong>Age provenance, imputation method, and candidate feature additions.</strong> <a href="#tbl-sensitivity" class="quarto-xref">Table&nbsp;<span>4.7</span></a> summarizes three further checks against the headline structural model.</p>
<div class="cell" data-execution_count="7">
<div id="tbl-sensitivity" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.7: Sensitivity checks against the headline structural model (full detail in tables/sensitivity_checks_all_families.csv).
</figcaption>
<div aria-describedby="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Pavement family</th>
<th data-quarto-table-cell-role="th">Headline R2</th>
<th data-quarto-table-cell-role="th">Age-verified (N)</th>
<th data-quarto-table-cell-role="th">Multi-imputation</th>
<th data-quarto-table-cell-role="th">Ext. features</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible</td>
<td>0.414</td>
<td>-0.43 (46)</td>
<td>0.41±0.00</td>
<td>0.346</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rigid, pooled</td>
<td>0.220</td>
<td>-0.04 (61)</td>
<td>0.22±0.01</td>
<td>0.187</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Rigid, JPCP only</td>
<td>-0.294</td>
<td>0.08 (42)</td>
<td>-0.33±0.01</td>
<td>-0.343</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Rigid, CRCP only</td>
<td>0.226</td>
<td>-0.34 (19)</td>
<td>0.18±0.04</td>
<td>0.150</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Restricting to records with a verified <code>INV_AGE.CONSTRUCTION_DATE</code> (excluding the age-proxy fallback) leaves only 19-61 sections per family — too few for a stable held-out estimate, and the resulting <span class="math inline">\(R^2\)</span> values swing widely, including strongly negative, in both directions relative to the full-sample headline figure. We read this as a sample-size artifact of the restriction itself rather than evidence that the age proxy is unreliable: with a test set of 4-12 sections, a handful of atypical records can dominate <span class="math inline">\(R^2\)</span>. A dedicated larger sample with universal construction-date coverage would be needed to test the age proxy’s effect directly. Multiple imputation, in contrast, gives a clear and reassuring answer: a five-draw stochastic multiple-imputation ensemble produces held-out <span class="math inline">\(R^2\)</span> within 0.003-0.05 of the single-imputation pipeline used throughout, for every family, with the largest discrepancy (CRCP-only, <span class="math inline">\(\pm0.038\)</span> SD) occurring in the family with the fewest sections. The single-pass MICE approach is not a material source of uncertainty relative to sampling variability at these sample sizes. Finally, adding a binary base-type indicator (granular vs.&nbsp;treated/stabilized base) and subgrade plasticity index to the structural feature set <em>reduces</em> held-out <span class="math inline">\(R^2\)</span> in every family (e.g., flexible: 0.414 → 0.346), rather than improving it. Plasticity index is populated for only 17-18% of records nationally, and imputing a variable at that missingness level appears to introduce more noise than signal once passed through the same training-fold-only imputer used for traffic and LTE; the binary base-type indicator, while fully observed, does not compensate. We report this as a genuine negative result: at least for these two candidate variables under this imputation strategy, expanding the structural feature set beyond the headline set does not improve on it.</p>
</section>
<section id="what-drives-iri-shap-feature-attribution" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="what-drives-iri-shap-feature-attribution"><span class="header-section-number">4.4</span> What drives IRI: SHAP feature attribution</h2>
<p><a href="#fig-shap-flex" class="quarto-xref">Figure&nbsp;<span>4.3</span></a> and <a href="#fig-shap-rigid" class="quarto-xref">Figure&nbsp;<span>4.4</span></a> show SHAP summary plots for the trained structural ensemble models. Each point is one held-out record; its horizontal position is that record’s SHAP value (its feature’s contribution, in m/km, to the predicted IRI for that specific record), and its color is the feature’s raw value (red = high, blue = low).</p>
<div id="fig-shap-flex" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-flex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/flexible_structural_shap_summary.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-flex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: SHAP summary — flexible pavements (structural model). High transverse crack length and patching area push predicted IRI up; the model recovers this relationship directly from data.
</figcaption>
</figure>
</div>
<div id="fig-shap-rigid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-rigid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/rigid_structural_shap_summary.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-rigid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: SHAP summary — rigid pavements, pooled (structural model). Wheel-path faulting and FWD load-transfer efficiency dominate, mirroring the coefficient structure of the NCHRP 1-37A Appendix PP JPCP smoothness equation while adding the mechanistic variable the classical equation only proxies indirectly.
</figcaption>
</figure>
</div>
<p>For flexible pavements, MEPDG transverse crack length is the single strongest predictor, followed by patching area and mean annual temperature — a data-driven confirmation of exactly the distress hierarchy that <span class="citation" data-cites="ara2004smoothness"><a href="references.html#ref-ara2004smoothness" role="doc-biblioref">[3]</a></span>’s hand-fit equation assumed by design, plus a climate interaction (temperature) that the fixed-form linear model cannot represent on its own. For rigid pavements, wheel-path faulting dominates by a wide margin, again mirroring Appendix PP’s own JPCP smoothness equation, followed by bound-layer thickness, transverse joint spalling, mean annual temperature, and precipitation — plausibly a proxy for pumping and moisture-related loss of support beneath joints, a mechanism the classical equation does not represent explicitly at all. FWD load-transfer efficiency ranks 10th of 14 features: a real, non-trivial contribution (consistent with the ablation result earlier in this chapter) rather than a dominant one, with low LTE (poor joint performance) pushing predicted IRI up, exactly the mechanistic pathway (loss of aggregate interlock or dowel efficiency → faulting → roughness) that Appendix PP’s equation encodes only implicitly through the faulting term alone. That LTE adds real signal without dominating is itself informative: faulting already captures most of what LTE would explain, since faulting is downstream of load-transfer loss — the two are correlated symptoms of the same mechanism, so LTE’s marginal contribution <em>on top of</em> faulting is modest by construction, not because load transfer is unimportant to rigid-pavement roughness.</p>
<p>The two climate variables warrant a more mechanistic reading than “climate matters.” For flexible pavements, mean annual temperature interacts with cracking rather than substituting for it in the SHAP plot (<a href="#fig-shap-flex" class="quarto-xref">Figure&nbsp;<span>4.3</span></a>): its effect is concentrated among records that already carry non-trivial transverse crack length, consistent with the well-established sensitivity of asphalt binder stiffness to temperature — a colder climate embrittles the binder and accelerates thermal (transverse) cracking for a given traffic and structural exposure, so temperature acts as an effect modifier on the crack-length–IRI relationship rather than an independent driver. For rigid pavements, precipitation’s contribution is concentrated among high-faulting records, which is the pattern implied by the classical erosion mechanism underlying pumping: water that infiltrates through joints or shoulders erodes fines from the base or subgrade, and repeated heavy axle loads pump the resulting slurry out from under the slab, progressively reducing support directly beneath the joint and increasing differential deflection across it. This is precisely the moisture-related loss-of-support mechanism that the M-E site factor <span class="math inline">\(SF = \text{Age} \times (1+FI) \times (1+P_{200})/10^6\)</span> <span class="citation" data-cites="ara2004smoothness"><a href="references.html#ref-ara2004smoothness" role="doc-biblioref">[3]</a></span> was constructed to proxy in aggregate rather than represent as a direct interaction with faulting; the SHAP-based model recovers the interaction directly from the joint distribution of precipitation and faulting rather than through a pre-specified multiplicative form.</p>
<p>Notably, the model recovers this structure <strong>without being given the M-E equation’s functional form in advance</strong> — it is discovered from the joint distribution of distress, climate, LTE, and IRI across hundreds of LTPP sections. This agreement with established mechanistic-empirical relationships is a useful check on the SHAP explanation itself: a data-driven attribution that recovers known pavement physics is more credible than one that cannot be reconciled with prior engineering knowledge.</p>


<!-- -->

<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-chen2016xgboost" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">T. Chen and C. Guestrin, <span>“<span>XGBoost</span>: A scalable tree boosting system,”</span> in <em>Proceedings of the 22nd ACM SIGKDD international conference on knowledge discovery and data mining</em>, 2016, pp. 785–794.</div>
</div>
<div id="ref-prokhorenkova2018catboost" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">L. Prokhorenkova, G. Gusev, A. Vorobev, A. V. Dorogush, and A. Gulin, <span>“<span>CatBoost</span>: Unbiased boosting with categorical features,”</span> in <em>Advances in neural information processing systems</em>, 2018.</div>
</div>
<div id="ref-ara2004smoothness" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">ARA, Inc., ERES Division, <span>“Guide for mechanistic-empirical design of new and rehabilitated pavement structures, appendix <span>PP</span>: Smoothness prediction for rigid pavements,”</span> National Cooperative Highway Research Program, Transportation Research Board, NCHRP Project 1-37A, 2004.</div>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-methods.html" class="pagination-link" aria-label="Data and Methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data and Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-discussion.html" class="pagination-link" aria-label="Discussion">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Discussion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results {#sec-results}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dataset summary</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>@tbl-dataset-summary summarizes the two assembled panels.</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-dataset-summary</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Summary of the assembled flexible and rigid LTPP IRI datasets (IRI min/max in tables/dataset_summary.csv)."</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/dataset_summary.csv"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">"N_records"</span>: <span class="st">"N"</span>, <span class="st">"N_sections"</span>: <span class="st">"Sections"</span>, <span class="st">"N_states"</span>: <span class="st">"States"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"IRI_mean"</span>: <span class="st">"IRI mean"</span>, <span class="st">"IRI_sd"</span>: <span class="st">"IRI sd"</span>, <span class="st">"Age_mean_yr"</span>: <span class="st">"Age mean (yr)"</span>})</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"Dataset"</span>, <span class="st">"N"</span>, <span class="st">"Sections"</span>, <span class="st">"States"</span>, <span class="st">"IRI mean"</span>, <span class="st">"IRI sd"</span>, <span class="st">"Age mean (yr)"</span>]]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>Both panels span a comparable range of in-service roughness (@fig-iri-dist), with the familiar right-skew of</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>a well-maintained highway network: most sections cluster between 1 and 2 m/km, with a thin tail of rougher</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>outliers that any predictive model has to work hard to capture.</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="al">![Distribution of IRI by pavement family.](../../plots/iri_distribution.png)</span>{#fig-iri-dist width=95%}</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>Age and IRI show the expected — and expectedly noisy — relationship (@fig-iri-age): both families roughen</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>somewhat with age, but the relationship is weak on its own, which is precisely the motivation for a</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>multivariate model that can weigh age against structure, climate, and accumulated distress simultaneously</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>rather than reading it off a single scatterplot.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="al">![IRI versus pavement age at the time of survey, by family.](../../plots/iri_vs_age.png)</span>{#fig-iri-age width=80%}</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model comparison</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>For every pavement family we fit three variants: the primary **structural** model (distress, structure,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>climate, and imputed traffic/LTE — no lagged IRI), a **traffic+LTE-ablated** structural model (the same rows</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>and split, minus those two imputed variables, isolating their marginal contribution), and an **operational**</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>model that adds the section's own previous IRI reading. @tbl-master reports held-out LightGBM performance</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>across all of them; @tbl-flex-metrics and @tbl-rigid-metrics give the full four-model comparison (linear,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>random forest, Optuna-tuned ANN, Optuna-tuned LightGBM) for the primary structural variant.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-master</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "LightGBM held-out R² across every pavement family and model variant (full N/RMSE detail in tables/master_lightgbm_comparison.csv)."</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/master_lightgbm_comparison.csv"</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Pavement family"</span>] <span class="op">=</span> df[<span class="st">"Pavement family"</span>].<span class="bu">str</span>.replace(<span class="st">"Rigid, pooled (JPCP+JRCP+CRCP)"</span>, <span class="st">"Rigid, pooled"</span>, regex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Pavement family"</span>] <span class="op">=</span> df[<span class="st">"Pavement family"</span>].<span class="bu">str</span>.replace(<span class="st">"Rigid, JPCP/JRCP only"</span>, <span class="st">"Rigid, JPCP only"</span>, regex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Variant"</span>] <span class="op">=</span> df[<span class="st">"Variant"</span>].<span class="bu">str</span>.replace(<span class="st">"Structural, traffic+LTE ablated"</span>, <span class="st">"No traffic/LTE"</span>, regex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Variant"</span>] <span class="op">=</span> df[<span class="st">"Variant"</span>].<span class="bu">str</span>.replace(<span class="st">"Operational (+ lagged IRI)"</span>, <span class="st">"Operational (lag)"</span>, regex<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"Pavement family"</span>, <span class="st">"Variant"</span>, <span class="st">"R2 (held-out)"</span>, <span class="st">"CV R2 mean"</span>, <span class="st">"CV R2 std"</span>]]</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-flex-metrics</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Structural model comparison — flexible (asphalt) pavements (MAE in tables/flexible_structural_model_metrics.csv)."</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.max_colwidth"</span>, <span class="va">None</span>)</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a>short_names <span class="op">=</span> {</span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MEPDG-style Linear Regression"</span>: <span class="st">"Linear (M-E style)"</span>,</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Random Forest"</span>: <span class="st">"Random Forest"</span>,</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ANN (MLP, Optuna-tuned)"</span>: <span class="st">"ANN (tuned)"</span>,</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Gradient-Boosted Ensemble (LightGBM, Optuna-tuned)"</span>: <span class="st">"LightGBM (tuned)"</span>,</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/flexible_structural_model_metrics.csv"</span>)</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Model"</span>] <span class="op">=</span> df[<span class="st">"Model"</span>].replace(short_names)</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[[<span class="st">"Model"</span>, <span class="st">"R2"</span>, <span class="st">"RMSE"</span>, <span class="st">"Train_time_s"</span>, <span class="st">"Speedup_vs_RF"</span>]].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>df.columns <span class="op">=</span> [<span class="st">"Model"</span>, <span class="st">"R2"</span>, <span class="st">"RMSE"</span>, <span class="st">"Time (s)"</span>, <span class="st">"vs RF"</span>]</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>df</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-rigid-metrics</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Structural model comparison — rigid pavements, pooled JPCP+JRCP+CRCP (MAE in tables/rigid_structural_model_metrics.csv)."</span></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>pd.set_option(<span class="st">"display.max_colwidth"</span>, <span class="va">None</span>)</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/rigid_structural_model_metrics.csv"</span>)</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"Model"</span>] <span class="op">=</span> df[<span class="st">"Model"</span>].replace(short_names)</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df[[<span class="st">"Model"</span>, <span class="st">"R2"</span>, <span class="st">"RMSE"</span>, <span class="st">"Train_time_s"</span>, <span class="st">"Speedup_vs_RF"</span>]].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>df.columns <span class="op">=</span> [<span class="st">"Model"</span>, <span class="st">"R2"</span>, <span class="st">"RMSE"</span>, <span class="st">"Time (s)"</span>, <span class="st">"vs RF"</span>]</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>df</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>Four findings emerge from @tbl-master. First, **Optuna tuning and MICE-style traffic/LTE imputation</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>meaningfully lift the structural models** relative to an untuned configuration with traffic/LTE excluded:</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>flexible-pavement $R^2$ rises from 0.333 to 0.414, and pooled rigid from 0.254 to 0.220 — the rigid figure is</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>a rare case where systematic tuning *did not* help (discussed below). Second, **removing traffic and LTE costs</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>a small but consistent</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>amount of accuracy everywhere** (flexible: 0.414 → 0.395; pooled rigid: 0.220 → 0.203), confirming they</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>carry real, non-redundant signal rather than being safely ignorable, without them being the dominant driver</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>either. Third, **the operational (lagged-IRI) variant is dramatically more accurate everywhere**</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>($R^2=0.698$ flexible, $0.391$ pooled rigid), which is expected — IRI is strongly autocorrelated within a</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>section — and is reported as a distinct, clearly-labeled model rather than folded into the "structural"</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>headline number, since the two answer different engineering questions (see @sec-methods). Fourth, **pooling</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>JPCP/JRCP and CRCP into one rigid model outperforms splitting them**: the JPCP/JRCP-only structural submodel</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>is actually *worse than predicting the mean* ($R^2=-0.294$, $n=118$ sections), and the CRCP-only submodel,</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>while positive ($R^2=0.226$), carries enormous cross-validation variance ($\pm0.246$) from having only 61</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>sections to work with. Splitting a modest sample into two smaller, noisier ones costs more in lost training</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>diversity than it gains in mechanism-specific homogeneity — an empirical answer, not an assumption, to</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>whether JPCP and CRCP should share a model.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>The rigid-pavement ANN is the clearest illustration of a tree ensemble's advantage in this small-section-count</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>regime: even after a 40-trial Optuna search over architecture, L2 regularization, and learning rate, it</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>manages only $R^2=0.009$ (pooled) to $R^2=-1.23$ (CRCP-only) on the structural task — worse, in the CRCP case,</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>than predicting the sample mean — while LightGBM's built-in leaf-wise regularization stays positive across</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>every rigid variant. Because the ANN is tuned against the same group-aware cross-validation objective as</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>LightGBM, its weaker performance reflects a genuine bias-variance trade-off in a few-hundred-section regime</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>rather than inadequate tuning of the baseline.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why the ensemble wins on speed, not just accuracy</span></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>LightGBM's histogram-based split-finding and leaf-wise tree growth make it substantially cheaper to train</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>than either the ANN (repeated gradient-descent epochs) or the random forest (hundreds of fully-grown,</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>un-pruned trees). Across every family and variant in @tbl-master, tuned LightGBM trains 1.7$\times$ to</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>9$\times$ faster than the random forest baseline. For an agency that wants to retrain its IRI model every time</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>a new LTPP release drops — as opposed to training it once and never touching it again — that speed advantage</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>compounds.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="fu">## Robustness and sensitivity checks</span></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>Five further checks accompany the headline structural model, addressing gradient-boosting implementation</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>choice, split methodology, age provenance, imputation method, and candidate feature additions in turn.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>**Gradient-boosting implementation.** @tbl-gbm-compare compares LightGBM against XGBoost <span class="co">[</span><span class="ot">@chen2016xgboost</span><span class="co">]</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>and CatBoost <span class="co">[</span><span class="ot">@prokhorenkova2018catboost</span><span class="co">]</span>, each independently tuned with a 25-trial Optuna search against the</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>same group-aware cross-validation objective as the headline model.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-gbm-compare</span></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Structural-model R² by gradient-boosting implementation."</span></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>pd.read_csv(<span class="st">"../../tables/gbm_implementation_comparison.csv"</span>)</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>LightGBM is the best- or near-best-performing implementation in three of four cases, and is within 0.03-0.06</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>$R^2$ of the best alternative in the fourth (JPCP/JRCP-only, where CatBoost edges ahead in an already</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>low-accuracy regime). The choice among modern gradient-boosting implementations does not change any of this</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>study's conclusions.</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>**Split methodology, and why its effect varies by family.** @tbl-leakage reports, for each family, the same</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>Optuna-tuned hyperparameters evaluated under a naive row-level split and under the group-aware split used</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>throughout this study, isolating the contribution of splitting strategy alone from any confound with</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>hyperparameter selection.</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-leakage</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Naive-split vs. group-aware-split R², same tuned hyperparameters."</span></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>pd.read_csv(<span class="st">"../../tables/leakage_comparison_all_families.csv"</span>)</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>The inflation from a naive split is not constant: it is negligible for flexible pavements (0.417 vs. 0.414)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>but substantial for rigid pavements, and largest of all for the JPCP/JRCP-only submodel (0.355 vs. -0.294, an</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>inflation of 0.649 $R^2$) — precisely the configuration whose structural feature set explains the least</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>genuine variance. This is consistent with a specific mechanism rather than a generic warning: when a naive</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>split allows repeated visits of the same section into both training and test data, the model can recover a</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>section's persistent, unmeasured characteristics from its training-set visits and apply that section-specific</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>signature to held-out visits of the *same* section. That recovery is most profitable, and therefore produces</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>the largest apparent accuracy gain, exactly where the measured covariates explain the smallest share of true</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>variance, since more of the outcome is then attributable to persistent section identity that only a naive</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>split allows to leak through. A well-tuned model evaluated on a well-explained outcome (flexible pavements)</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>has comparatively little unexplained section-specific variance left for a naive split to exploit; a model</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>facing a poorly-explained outcome (JPCP/JRCP structural roughness) has a great deal, and a naive split</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>rewards memorizing it. This is a more specific and testable claim than the coarser observation that an early,</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>less-regularized configuration of the flexible-pavement model showed a large naive-vs-grouped gap (0.52 vs.</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>0.33): leakage-driven inflation should scale with the fraction of outcome variance the structural features</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>fail to explain, a pattern @tbl-leakage confirms across four independently-tuned models spanning a wide range</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>of explanatory power.</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>**Age provenance, imputation method, and candidate feature additions.** @tbl-sensitivity summarizes three</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>further checks against the headline structural model.</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-sensitivity</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Sensitivity checks against the headline structural model (full detail in tables/sensitivity_checks_all_families.csv)."</span></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/sensitivity_checks_all_families.csv"</span>)</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>compact <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Pavement family"</span>: df[<span class="st">"Pavement family"</span>].<span class="bu">str</span>.replace(<span class="st">"Rigid, JPCP/JRCP only"</span>, <span class="st">"Rigid, JPCP only"</span>, regex<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Headline R2"</span>: df[<span class="st">"Headline R2"</span>],</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Age-verified (N)"</span>: [<span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:.2f}</span><span class="ss"> (</span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">)"</span> <span class="cf">for</span> r, n <span class="kw">in</span></span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>                          <span class="bu">zip</span>(df[<span class="st">"Age-verified-only R2"</span>], df[<span class="st">"Age-verified N sections"</span>])],</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Multi-imputation"</span>: [<span class="ss">f"</span><span class="sc">{</span>m<span class="sc">:.2f}</span><span class="ss">±</span><span class="sc">{</span>s<span class="sc">:.2f}</span><span class="ss">"</span> <span class="cf">for</span> m, s <span class="kw">in</span></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>                          <span class="bu">zip</span>(df[<span class="st">"Multi-imputation R2 mean"</span>], df[<span class="st">"Multi-imputation R2 std"</span>])],</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Ext. features"</span>: df[<span class="st">"Extended-features R2"</span>],</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>compact</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>Restricting to records with a verified <span class="in">`INV_AGE.CONSTRUCTION_DATE`</span> (excluding the age-proxy fallback) leaves</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>only 19-61 sections per family — too few for a stable held-out estimate, and the resulting $R^2$ values swing</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>widely, including strongly negative, in both directions relative to the full-sample headline figure. We read</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>this as a sample-size artifact of the restriction itself rather than evidence that the age proxy is</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>unreliable: with a test set of 4-12 sections, a handful of atypical records can dominate $R^2$. A dedicated</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>larger sample with universal construction-date coverage would be needed to test the age proxy's effect</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>directly. Multiple imputation, in contrast, gives a clear and reassuring answer: a five-draw stochastic</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>multiple-imputation ensemble produces held-out $R^2$ within 0.003-0.05 of the single-imputation pipeline used</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>throughout, for every family, with the largest discrepancy (CRCP-only, $\pm0.038$ SD) occurring in the</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>family with the fewest sections. The single-pass MICE approach is not a material source of uncertainty</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>relative to sampling variability at these sample sizes. Finally, adding a binary base-type indicator</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>(granular vs. treated/stabilized base) and subgrade plasticity index to the structural feature set *reduces*</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>held-out $R^2$ in every family (e.g., flexible: 0.414 → 0.346), rather than improving it. Plasticity index is</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>populated for only 17-18% of records nationally, and imputing a variable at that missingness level appears to</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>introduce more noise than signal once passed through the same training-fold-only imputer used for traffic and</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>LTE; the binary base-type indicator, while fully observed, does not compensate. We report this as a genuine</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>negative result: at least for these two candidate variables under this imputation strategy, expanding the</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>structural feature set beyond the headline set does not improve on it.</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="fu">## What drives IRI: SHAP feature attribution</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>@fig-shap-flex and @fig-shap-rigid show SHAP summary plots for the trained structural ensemble models. Each</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>point is one held-out record; its horizontal position is that record's SHAP value (its feature's contribution,</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>in m/km, to the predicted IRI for that specific record), and its color is the feature's raw value (red = high,</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>blue = low).</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="al">![SHAP summary — flexible pavements (structural model). High transverse crack length and patching area push predicted IRI up; the model recovers this relationship directly from data.](../../plots/flexible_structural_shap_summary.png)</span>{#fig-shap-flex width=90%}</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="al">![SHAP summary — rigid pavements, pooled (structural model). Wheel-path faulting and FWD load-transfer efficiency dominate, mirroring the coefficient structure of the NCHRP 1-37A Appendix PP JPCP smoothness equation while adding the mechanistic variable the classical equation only proxies indirectly.](../../plots/rigid_structural_shap_summary.png)</span>{#fig-shap-rigid width=90%}</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>For flexible pavements, MEPDG transverse crack length is the single strongest predictor, followed by patching</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>area and mean annual temperature — a data-driven confirmation of exactly the distress hierarchy that</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>@ara2004smoothness's hand-fit equation assumed by design, plus a climate interaction (temperature) that the</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>fixed-form linear model cannot represent on its own. For rigid pavements, wheel-path faulting dominates by a</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>wide margin, again mirroring Appendix PP's own JPCP smoothness equation, followed by bound-layer thickness,</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>transverse joint spalling, mean annual temperature, and precipitation — plausibly a proxy for pumping and</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>moisture-related loss of support beneath joints, a mechanism the classical equation does not represent</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>explicitly at all. FWD load-transfer efficiency ranks 10th of 14 features: a real, non-trivial contribution</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>(consistent with the ablation result earlier in this chapter) rather than a dominant one, with low LTE (poor</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>joint performance) pushing</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>predicted IRI up, exactly the mechanistic pathway (loss of aggregate interlock or dowel efficiency → faulting</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>→ roughness) that Appendix PP's equation encodes only implicitly through the faulting term alone. That LTE</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>adds real signal without dominating is itself informative: faulting already captures most of what LTE would</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>explain, since faulting is downstream of load-transfer loss — the two are correlated symptoms of the same</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>mechanism, so LTE's marginal contribution *on top of* faulting is modest by construction, not because load</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>transfer is unimportant to rigid-pavement roughness.</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>The two climate variables warrant a more mechanistic reading than "climate matters." For flexible pavements,</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>mean annual temperature interacts with cracking rather than substituting for it in the SHAP plot (@fig-shap-flex):</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>its effect is concentrated among records that already carry non-trivial transverse crack length, consistent</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>with the well-established sensitivity of asphalt binder stiffness to temperature — a colder climate embrittles</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>the binder and accelerates thermal (transverse) cracking for a given traffic and structural exposure, so</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>temperature acts as an effect modifier on the crack-length–IRI relationship rather than an independent driver.</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>For rigid pavements, precipitation's contribution is concentrated among high-faulting records, which is the</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>pattern implied by the classical erosion mechanism underlying pumping: water that infiltrates through joints</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>or shoulders erodes fines from the base or subgrade, and repeated heavy axle loads pump the resulting slurry</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>out from under the slab, progressively reducing support directly beneath the joint and increasing differential</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>deflection across it. This is precisely the moisture-related loss-of-support mechanism that the M-E site</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>factor $SF = \text{Age} \times (1+FI) \times (1+P_{200})/10^6$ <span class="co">[</span><span class="ot">@ara2004smoothness</span><span class="co">]</span> was constructed to</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>proxy in aggregate rather than represent as a direct interaction with faulting; the SHAP-based model recovers</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>the interaction directly from the joint distribution of precipitation and faulting rather than through a</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>pre-specified multiplicative form.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>Notably, the model recovers this structure **without being given the M-E equation's functional form in</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>advance** — it is discovered from the joint distribution of distress, climate, LTE, and IRI across hundreds of</span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>LTPP sections. This agreement with established mechanistic-empirical relationships is a useful check on the</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>SHAP explanation itself: a data-driven attribution that recovers known pavement physics is more credible than</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>one that cannot be reconciled with prior engineering knowledge.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><em>Beyond Asphalt</em> was written by Seyed Saber Naseralavi, Ali Reza Ghanizadeh, and Akram Mazaheri.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/sabernaseralavi-60/2026_International-Roughness-Index-Prediction-Using-the-LTPP/edit/master/04-results.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/sabernaseralavi-60/2026_International-Roughness-Index-Prediction-Using-the-LTPP/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a>, in the style of <a href="https://r4ds.hadley.nz/">R for Data Science</a>.</p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>