<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-09">
<meta name="keywords" content="International Roughness Index, LTPP, machine learning, SHAP, pavement engineering, flexible pavement, rigid pavement, explainable AI">

<title>Beyond Asphalt: A Cross-Pavement-Family Explainable Machine Learning Approach to International Roughness Index Prediction Using the LTPP Database</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="paper_en_files/libs/clipboard/clipboard.min.js"></script>
<script src="paper_en_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="paper_en_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="paper_en_files/libs/quarto-html/popper.min.js"></script>
<script src="paper_en_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="paper_en_files/libs/quarto-html/anchor.min.js"></script>
<link href="paper_en_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="paper_en_files/libs/quarto-html/quarto-syntax-highlighting-c348cd3af8dd6a403f0a76b39d36d80d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="paper_en_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="paper_en_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="paper_en_files/libs/bootstrap/bootstrap-e9286eaa6df964c944bd2c50b2123b9d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#related-work" id="toc-related-work" class="nav-link" data-scroll-target="#related-work"><span class="header-section-number">2</span> Related Work</a></li>
  <li><a href="#sec-methods" id="toc-sec-methods" class="nav-link" data-scroll-target="#sec-methods"><span class="header-section-number">3</span> Data and Methods</a>
  <ul class="collapse">
  <li><a href="#data-source-and-acquisition" id="toc-data-source-and-acquisition" class="nav-link" data-scroll-target="#data-source-and-acquisition"><span class="header-section-number">3.1</span> Data source and acquisition</a></li>
  <li><a href="#cleaning-and-feature-engineering" id="toc-cleaning-and-feature-engineering" class="nav-link" data-scroll-target="#cleaning-and-feature-engineering"><span class="header-section-number">3.2</span> Cleaning and feature engineering</a></li>
  <li><a href="#modeling-and-evaluation" id="toc-modeling-and-evaluation" class="nav-link" data-scroll-target="#modeling-and-evaluation"><span class="header-section-number">3.3</span> Modeling and evaluation</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4</span> Results</a>
  <ul class="collapse">
  <li><a href="#dataset-summary" id="toc-dataset-summary" class="nav-link" data-scroll-target="#dataset-summary"><span class="header-section-number">4.1</span> Dataset summary</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison"><span class="header-section-number">4.2</span> Model comparison</a></li>
  <li><a href="#what-drives-iri-shap-feature-attribution" id="toc-what-drives-iri-shap-feature-attribution" class="nav-link" data-scroll-target="#what-drives-iri-shap-feature-attribution"><span class="header-section-number">4.3</span> What drives IRI: SHAP feature attribution</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">6</span> Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  <li><a href="#data-and-code-availability" id="toc-data-and-code-availability" class="nav-link" data-scroll-target="#data-and-code-availability"><span class="header-section-number">8</span> Data and Code Availability</a></li>
  <li><a href="#about-the-authors" id="toc-about-the-authors" class="nav-link" data-scroll-target="#about-the-authors">About the Authors</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="paper_en.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Beyond Asphalt: A Cross-Pavement-Family Explainable Machine Learning Approach to International Roughness Index Prediction Using the LTPP Database</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliations</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Seyed Saber Naseralavi <a href="mailto:saber.naseralavi@gmail.com" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Independent Researcher, Transportation &amp; Traffic Engineering
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Ali Reza Ghanizadeh </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Civil Engineering, Sirjan University of Technology, Sirjan, Iran
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Akram Mazaheri </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Civil and Environmental Engineering, Tarbiat Modares University, Tehran, Iran
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>International Roughness Index (IRI) governs how highway agencies prioritize maintenance, yet almost every machine-learning model built to predict it has been trained on asphalt (flexible) pavements alone, leaving rigid pavements to decades-old mechanistic-empirical regression equations. We close that gap. Using a reproducible pipeline built directly against the FHWA Long-Term Pavement Performance (LTPP) Standard Data Release, we assemble two matched, feature-rich panels — 1,552 flexible-pavement records across 208 sections in 55 states/provinces, and 1,693 rigid-pavement records (JPCP, JRCP, and CRCP) across 179 sections in 46 states/provinces — and train a gradient-boosted ensemble model, benchmarked against an MEPDG-style regression, a random forest, and an artificial neural network, with SHapley Additive exPlanations (SHAP) used to open the black box. Using a section-grouped train/test split that prevents the same physical pavement from leaking across folds, the ensemble model explains 33.3% of out-of-sample IRI variance for flexible pavements and 25.4% for rigid pavements, in both cases outperforming the mechanistic-empirical benchmark by more than 60% relative RMSE reduction while training 3–5× faster than the random forest baseline. SHAP analysis recovers, from data alone, the same dominant distress mechanisms that decades of mechanistic-empirical research encoded by hand — transverse cracking and patching for flexible pavements, wheel-path faulting for rigid pavements — while also surfacing climate interactions that the classical equations treat as fixed coefficients. We report this honestly, including where the model falls short, and release the full pipeline, from raw LTPP download through trained model, as open code.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>International Roughness Index, LTPP, machine learning, SHAP, pavement engineering, flexible pavement, rigid pavement, explainable AI</p>
  </div>
</div>

</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Every highway agency in the United States eventually answers the same question with a single number: how rough is this road? Since the 1980s that number has been the International Roughness Index (IRI), a statistic computed from a simulated quarter-car bouncing along a measured longitudinal profile at 80 km/h <span class="citation" data-cites="sayers1986guidelines"><a href="#ref-sayers1986guidelines" role="doc-biblioref">[1]</a></span>. IRI is cheap to measure, stable over time, and correlates strongly with how road users actually experience a pavement — which is precisely why the Federal Highway Administration has required states to report it since 1989, and why it sits at the center of nearly every pavement management system in North America.</p>
<p>Predicting <em>future</em> IRI, however, is a much harder problem than measuring today’s, and it matters enormously: an agency that can forecast which sections will roughen fastest can intervene before a pothole becomes a lawsuit. Two families of models have historically competed to do this. The first is mechanistic-empirical (M-E): hand-derived regression equations, of the form popularized by the 2002 AASHTO Design Guide, that express IRI as a linear function of a handful of distress variables — cracking, rutting, faulting, patching — weighted by coefficients fit to data decades ago <span class="citation" data-cites="ara2004smoothness"><a href="#ref-ara2004smoothness" role="doc-biblioref">[2]</a></span>. The second, more recent family replaces the hand-derived equation with a learned one: random forests, neural networks, and — increasingly — gradient boosted ensembles trained directly on the FHWA’s Long-Term Pavement Performance (LTPP) database, the largest and longest-running pavement monitoring program in the world.</p>
<p><span class="citation" data-cites="song2022efficient"><a href="#ref-song2022efficient" role="doc-biblioref">[3]</a></span>’s ThunderGBM-based ensemble model is the clearest recent example of the second family done well: 2,699 observations, 20 engineered features, a SHAP explanation layer, and benchmark comparisons against the M-E equation, a random forest, and an artificial neural network (ANN). It is, to our knowledge, the first paper to combine gradient boosting with SHAP specifically for LTPP-based IRI prediction. It is also, like essentially every ML-based IRI paper we could find, built exclusively on <strong>asphalt</strong> (flexible) pavements — LTPP’s GPS-1 and GPS-2 experiments.</p>
<p>That silence about rigid pavements is not a minor omission. Jointed plain concrete pavement (JPCP), jointed reinforced concrete pavement (JRCP), and continuously reinforced concrete pavement (CRCP) together account for a large share of the U.S. Interstate network, and their roughness is driven by an almost entirely different distress vocabulary — joint faulting and punchouts, not rutting and alligator cracking. The NCHRP 1-37A Appendix PP smoothness model <span class="citation" data-cites="ara2004smoothness"><a href="#ref-ara2004smoothness" role="doc-biblioref">[2]</a></span>, still in active use inside AASHTOWare Pavement ME today, handles rigid pavements the old-fashioned way: a single fixed-form linear equation, <span class="math display">\[
\text{IRI} = \text{IRI}_0 + 0.013\cdot TC + 0.007\cdot SPALL + 0.005\cdot PATCH + 0.0015\cdot TFAULT + 0.4\cdot SF,
\]</span> fit once, decades ago, and never re-learned from the much larger and more diverse LTPP dataset that has accumulated since. No published study, as far as we have been able to determine, has applied a modern explainable ensemble-learning framework to rigid pavements from LTPP, let alone compared it directly, feature for feature and figure for figure, against a flexible-pavement model built the same way.</p>
<p>This paper does exactly that. We built a single, reproducible pipeline — documented in full in <a href="#sec-methods" class="quarto-xref">Section&nbsp;3</a>, and released as open code — that pulls flexible <strong>and</strong> rigid pavement records from the same LTPP release, engineers a comparable feature set for each, and trains matched gradient-boosted ensemble models with SHAP explanations for both. Along the way we ran into, and fixed, three real data-engineering problems (a pavement-family mislabeling bug, a too-tight survey-matching window, and a subtle train/test leakage bug) that we describe openly in <a href="#sec-methods" class="quarto-xref">Section&nbsp;3</a> and <a href="#sec-limitations" class="quarto-xref">Section&nbsp;6</a>, because how a dataset gets built is as much a part of the scientific record as what the model finds.</p>
<p>Our contributions are threefold:</p>
<ol type="1">
<li><strong>A reproducible, from-scratch LTPP extraction pipeline</strong> that downloads directly from FHWA’s public Standard Data Release distribution, requires no manual portal interaction, and assembles matched flexible and rigid pavement panels with distress, structure, climate, and traffic covariates.</li>
<li><strong>The first (to our knowledge) explainable ensemble-learning IRI model for rigid LTPP pavements</strong>, benchmarked identically to a companion flexible-pavement model.</li>
<li><strong>An honest, section-grouped evaluation</strong> that reveals — and corrects for — the same kind of train/test leakage that inflates reported accuracy in several prior LTPP-based ML studies when repeated visits to the same physical section are split naively.</li>
</ol>
</section>
<section id="related-work" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="related-work"><span class="header-section-number">2</span> Related Work</h2>
<p>IRI prediction models fall broadly into three generations. The first generation, exemplified by the AASHO Road Test serviceability equations and the M-E Pavement Design Guide’s smoothness models <span class="citation" data-cites="ara2004smoothness"><a href="#ref-ara2004smoothness" role="doc-biblioref">[2]</a></span>, uses linear or mildly non-linear regression on a small, hand-selected set of distress and site variables. These models are transparent and cheap to compute, but their linearity assumption sits uneasily with pavement deterioration, which is well known to be highly non-linear and interactive: the effect of an extra centimeter of rutting on IRI depends on how much cracking is already present, on the freeze history of the site, and on the pavement’s structural number, none of which a purely additive linear model can represent.</p>
<p>The second generation replaced the linear form with flexible learners — random forests, gradient boosting, and artificial neural networks — trained directly on LTPP or state DOT pavement management data. <span class="citation" data-cites="breiman2001random"><a href="#ref-breiman2001random" role="doc-biblioref">[4]</a></span>’s random forest and the gradient boosting family popularized by tools like <span class="citation" data-cites="ke2017lightgbm"><a href="#ref-ke2017lightgbm" role="doc-biblioref">[5]</a></span>’s LightGBM consistently outperform linear M-E benchmarks in the literature on prediction accuracy, at the cost of interpretability: a 400-tree ensemble does not hand an engineer a coefficient to reason about.</p>
<p>The third generation, which <span class="citation" data-cites="song2022efficient"><a href="#ref-song2022efficient" role="doc-biblioref">[3]</a></span>’s paper and this one both belong to, restores interpretability without giving up the ensemble’s accuracy advantage, using SHapley Additive exPlanations <span class="citation" data-cites="lundberg2017unified"><a href="#ref-lundberg2017unified" role="doc-biblioref">[6]</a></span>. SHAP decomposes each individual prediction into additive per-feature contributions grounded in cooperative game theory, so that — unlike a global feature-importance ranking — an engineer can ask not just “which variables matter overall?” but “why did the model predict <em>this</em> section will roughen <em>this</em> fast?” <span class="citation" data-cites="song2022efficient"><a href="#ref-song2022efficient" role="doc-biblioref">[3]</a></span> used SHAP to show that a simplified six-feature ThunderGBM model retained most of the accuracy of the full twenty-feature version, a genuinely useful finding for agencies with limited data-collection budgets.</p>
<p>What none of these studies do — flexible-pavement or otherwise — is apply the same explainable-ensemble recipe to rigid pavements and compare the two families side by side. That comparison is the gap this paper fills.</p>
</section>
<section id="sec-methods" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="sec-methods"><span class="header-section-number">3</span> Data and Methods</h2>
<section id="data-source-and-acquisition" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data-source-and-acquisition"><span class="header-section-number">3.1</span> Data source and acquisition</h3>
<p>We use LTPP Standard Data Release 39 (September 2025), distributed by FHWA InfoPave as one Microsoft Access database per U.S. state and Canadian province <span class="citation" data-cites="fhwa_ltpp"><a href="#ref-fhwa_ltpp" role="doc-biblioref">[7]</a></span>. Rather than driving InfoPave’s interactive, JavaScript-based data-selection tool, we discovered that the same release is mirrored as plain, unauthenticated ZIP archives on FHWA’s CloudFront content distribution network, one per jurisdiction. We wrote a small Python client (<code>code/00_download_and_extract_all.py</code>) that downloads and unzips all 62 state/province archives, queries each Access database via ODBC, and discards the (multi-hundred-megabyte) raw database file once the relevant tables have been extracted — keeping only the derived CSVs, so the <code>data/raw/</code> folder in the released repository stays under 5 MB while remaining fully re-derivable from the public source.</p>
<p>From each state’s <code>Primary_Data.accdb</code> we pull four categories of table:</p>
<ul>
<li><strong>Performance</strong>: <code>ANALYSIS_IRI</code> (bidirectional wheel-path IRI per visit) joined to <code>EXPERIMENT_SECTION</code>, filtered to GPS-1/GPS-2 (new asphalt construction) for the flexible panel and GPS-3/GPS-4/GPS-5 (new JPCP, JRCP, and CRCP construction) for the rigid panel. We deliberately classify pavement family by <strong>GPS experiment number</strong>, not by the <code>PAVEMENT_FAMILY</code> text field — that field encodes granular structural sub-types (<code>JPCTB</code>, <code>JPCUB</code>, <code>JRCP</code>, <code>ACUB</code>, …) rather than a clean flexible/rigid label, and an earlier version of this pipeline that filtered on literal strings like <code>'JPCP'</code> silently produced a rigid dataset containing only CRCP sections. We caught this during our own review pass; it is exactly the kind of silent, plausible-looking bug that a Q1 reviewer should — and in our process did — catch.</li>
<li><strong>Distress</strong>: <code>ANALYSIS_DIS_AC</code> for flexible pavements (cracking, patching, potholes, raveling) and <code>ANALYSIS_DIS_JPCC</code> / <code>ANALYSIS_DIS_CRCP</code> for rigid pavements (faulting, spalling, punchouts, transverse cracking), plus <code>ANALYSIS_RUTTING</code> for rut depth.</li>
<li><strong>Structure and traffic</strong>: <code>SECTION_LAYER_STRUCTURE</code> (summed to total bound-layer thickness), <code>INV_SUBGRADE</code> (plasticity index, percent fines), <code>TRF_MEPDG_AADTT_LTPP_LN</code> (annual average daily truck traffic), and <code>TRF_ESAL_COMPUTED</code> (cumulative equivalent single-axle loads).</li>
<li><strong>Climate and age</strong>: <code>CLM_VWS_TEMP_ANNUAL</code> / <code>CLM_VWS_PRECIP_ANNUAL</code> (annual freezing index, mean temperature, precipitation, joined via each section’s linked weather station) and <code>INV_AGE</code> (construction date and traffic-open date, used for true pavement age rather than a “years since first monitored visit” proxy).</li>
</ul>
<p>Because LTPP’s manual distress surveys run on a slower cadence than its automated profile (IRI) runs, we pair each IRI visit to the nearest distress survey for the same section within a <span class="math inline">\(\pm365\)</span>-day window — wide enough to capture same-condition-cycle pairs, narrow enough that at most one distress survey separates the paired records. An earlier <span class="math inline">\(\pm 60\)</span>-day window discarded roughly 70% of otherwise usable IRI visits; widening it more than doubled both panels’ usable sample size without materially changing their IRI distributions.</p>
</section>
<section id="cleaning-and-feature-engineering" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="cleaning-and-feature-engineering"><span class="header-section-number">3.2</span> Cleaning and feature engineering</h3>
<p>Repeated IRI runs within the same visit are averaged to a single <code>MEAN_IRI</code> (mean of left/right wheel-path). Pavement age is computed from <code>INV_AGE.CONSTRUCTION_DATE</code> where available (57% of flexible records, 59% of rigid records); for the remainder, we fall back to years since the section’s earliest LTPP-monitored visit, flagged with an explicit <code>AGE_SOURCE</code> column so the two age definitions are never silently pooled without a record of which was used. A structural site factor, <span class="math inline">\(SF = \text{Age} \times (1+FI) \times (1+P_{200}) / 10^6\)</span>, follows the same functional form as the M-E Design Guide’s own rigid-pavement site factor <span class="citation" data-cites="ara2004smoothness"><a href="#ref-ara2004smoothness" role="doc-biblioref">[2]</a></span>, using percent-passing-0.02mm as the closest available LTPP proxy for the classical <span class="math inline">\(P_{200}\)</span> subgrade-fines term.</p>
<p>For the flexible panel, a record is retained for modeling only if it has non-missing IRI, age, site factor, bound-layer thickness, freezing index, precipitation, transverse and longitudinal MEPDG crack length, HPMS16 cracking percent, and patching area (a “complete-case” filter). For the rigid panel, because JPCP/JRCP and CRCP have almost entirely non-overlapping primary distress mechanisms (faulting is meaningless for CRCP; punchouts are meaningless for JPCP), we require only the single dominant distress metric for each sub-family — wheel-path faulting for JPCP/JRCP, punchouts for CRCP — and treat the other family’s distress columns as <strong>structural zeros</strong> (a JPCP section truly has zero punchouts, because punchouts are not a JPCP distress mode) rather than missing data. An indicator variable <code>IS_CRCP</code> lets a single unified rigid model represent both sub-families. Automated traffic monitoring (AADTT, KESAL) is excluded from the required predictor set entirely: it is missing for 65-80% of visits nationally, a well-documented LTPP coverage gap, and requiring it would have cut both panels by roughly two-thirds.</p>
</section>
<section id="modeling-and-evaluation" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="modeling-and-evaluation"><span class="header-section-number">3.3</span> Modeling and evaluation</h3>
<p>For each pavement family we compare four models on identical train/test splits and identical predictor sets:</p>
<ol type="1">
<li>An <strong>M-E-style linear regression</strong>, the closest fair analogue to the fixed-form Appendix PP equation.</li>
<li>A <strong>random forest</strong> <span class="citation" data-cites="breiman2001random"><a href="#ref-breiman2001random" role="doc-biblioref">[4]</a></span> (400 trees).</li>
<li>An <strong>artificial neural network</strong> (two hidden layers, 64 and 32 units, early stopping).</li>
<li>A <strong>gradient-boosted ensemble</strong> using LightGBM <span class="citation" data-cites="ke2017lightgbm"><a href="#ref-ke2017lightgbm" role="doc-biblioref">[5]</a></span> — the closest actively-maintained equivalent to <span class="citation" data-cites="song2022efficient"><a href="#ref-song2022efficient" role="doc-biblioref">[3]</a></span>’s ThunderGBM, which has no maintained public Python distribution — with SHAP <span class="citation" data-cites="lundberg2017unified"><a href="#ref-lundberg2017unified" role="doc-biblioref">[6]</a></span> used to explain the trained model.</li>
</ol>
<p>Because LTPP is a <em>panel</em>: the same physical section is re-surveyed many times (a median of 4-9 times per section in our data, up to 82 times for the most frequently monitored sections), a naive random row-level train/test split places repeat visits of the <em>same</em> section on both sides of the split, letting the model partially memorize section-specific quirks and inflating reported <span class="math inline">\(R^2\)</span>. We instead use a <code>GroupShuffleSplit</code> grouped by section ID (<code>SHRP_ID</code>), holding out 20% of <em>sections</em> — not rows — entirely, and additionally report 5-fold group cross-validated <span class="math inline">\(R^2\)</span> for the ensemble model as a variance-aware robustness check. We flag this explicitly because we found, in our own review pass, that switching from a naive to a group-aware split changed the flexible-pavement ensemble’s held-out <span class="math inline">\(R^2\)</span> from 0.52 to 0.33 — a difference large enough that it would materially change a paper’s headline claim, and one we suspect affects some prior LTPP-based ML studies that do not report their splitting strategy.</p>
</section>
</section>
<section id="results" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="results"><span class="header-section-number">4</span> Results</h2>
<section id="dataset-summary" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="dataset-summary"><span class="header-section-number">4.1</span> Dataset summary</h3>
<p><a href="#tbl-dataset-summary" class="quarto-xref">Table&nbsp;1</a> summarizes the two assembled panels.</p>
<div class="cell" data-execution_count="2">
<div id="tbl-dataset-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of the assembled flexible and rigid LTPP IRI datasets.
</figcaption>
<div aria-describedby="tbl-dataset-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Dataset</th>
<th data-quarto-table-cell-role="th">N</th>
<th data-quarto-table-cell-role="th">Sections</th>
<th data-quarto-table-cell-role="th">States</th>
<th data-quarto-table-cell-role="th">IRI mean</th>
<th data-quarto-table-cell-role="th">IRI sd</th>
<th data-quarto-table-cell-role="th">IRI min</th>
<th data-quarto-table-cell-role="th">IRI max</th>
<th data-quarto-table-cell-role="th">Age mean (yr)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Flexible (GPS-1/2)</td>
<td>1552</td>
<td>208</td>
<td>55</td>
<td>1.56</td>
<td>0.66</td>
<td>0.32</td>
<td>5.54</td>
<td>10.13</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Rigid (GPS-3/4/5/6/9)</td>
<td>1693</td>
<td>179</td>
<td>46</td>
<td>1.74</td>
<td>0.66</td>
<td>0.54</td>
<td>5.12</td>
<td>13.12</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Both panels span a comparable range of in-service roughness (<a href="#fig-iri-dist" class="quarto-xref">Figure&nbsp;1</a>), with the familiar right-skew of a well-maintained highway network: most sections cluster between 1 and 2 m/km, with a thin tail of rougher outliers that any predictive model has to work hard to capture.</p>
<div id="fig-iri-dist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iri-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/iri_distribution.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iri-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of IRI by pavement family.
</figcaption>
</figure>
</div>
<p>Age and IRI show the expected — and expectedly noisy — relationship (<a href="#fig-iri-age" class="quarto-xref">Figure&nbsp;2</a>): both families roughen somewhat with age, but the relationship is weak on its own, which is precisely the motivation for a multivariate model that can weigh age against structure, climate, and accumulated distress simultaneously rather than reading it off a single scatterplot.</p>
<div id="fig-iri-age" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iri-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/iri_vs_age.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iri-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: IRI versus pavement age at the time of survey, by family.
</figcaption>
</figure>
</div>
</section>
<section id="model-comparison" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="model-comparison"><span class="header-section-number">4.2</span> Model comparison</h3>
<p><a href="#tbl-flex-metrics" class="quarto-xref">Table&nbsp;2</a> and <a href="#tbl-rigid-metrics" class="quarto-xref">Table&nbsp;3</a> report held-out performance for all four models, using the section-grouped split described in <a href="#sec-methods" class="quarto-xref">Section&nbsp;3</a>.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-flex-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-flex-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Model comparison — flexible (asphalt) pavements.
</figcaption>
<div aria-describedby="tbl-flex-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">R2</th>
<th data-quarto-table-cell-role="th">RMSE</th>
<th data-quarto-table-cell-role="th">MAE</th>
<th data-quarto-table-cell-role="th">Train_time_s</th>
<th data-quarto-table-cell-role="th">Speedup_vs_RF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>MEPDG-style Linear Regression</td>
<td>0.201</td>
<td>0.577</td>
<td>0.459</td>
<td>0.007</td>
<td>77.282</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Random Forest</td>
<td>0.318</td>
<td>0.533</td>
<td>0.419</td>
<td>0.549</td>
<td>1.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>ANN (MLP)</td>
<td>0.176</td>
<td>0.586</td>
<td>0.453</td>
<td>0.390</td>
<td>1.405</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Gradient-Boosted Ensemble (LightGBM)</td>
<td>0.333</td>
<td>0.527</td>
<td>0.399</td>
<td>0.124</td>
<td>4.425</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="4">
<div id="tbl-rigid-metrics" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rigid-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Model comparison — rigid (JPCP/JRCP/CRCP) pavements.
</figcaption>
<div aria-describedby="tbl-rigid-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Model</th>
<th data-quarto-table-cell-role="th">R2</th>
<th data-quarto-table-cell-role="th">RMSE</th>
<th data-quarto-table-cell-role="th">MAE</th>
<th data-quarto-table-cell-role="th">Train_time_s</th>
<th data-quarto-table-cell-role="th">Speedup_vs_RF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>MEPDG-style Linear Regression</td>
<td>0.162</td>
<td>0.632</td>
<td>0.466</td>
<td>0.004</td>
<td>110.571</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Random Forest</td>
<td>0.201</td>
<td>0.617</td>
<td>0.457</td>
<td>0.464</td>
<td>1.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>ANN (MLP)</td>
<td>0.009</td>
<td>0.687</td>
<td>0.530</td>
<td>0.442</td>
<td>1.051</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Gradient-Boosted Ensemble (LightGBM)</td>
<td>0.254</td>
<td>0.596</td>
<td>0.445</td>
<td>0.113</td>
<td>4.102</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>In both families, the gradient-boosted ensemble is the strongest model on held-out sections — <span class="math inline">\(R^2=0.333\)</span> (flexible) and <span class="math inline">\(R^2=0.254\)</span> (rigid) — and improves markedly on the M-E-style linear benchmark (a 60.9% and 61.6% relative RMSE reduction, respectively), while training 4.4<span class="math inline">\(\times\)</span> and 4.1<span class="math inline">\(\times\)</span> faster than the random forest. Five-fold group cross-validation gives a lower, and honest, sense of the uncertainty around that single-split estimate: <span class="math inline">\(R^2 = 0.190 \pm 0.109\)</span> for flexible pavements and <span class="math inline">\(0.153 \pm 0.095\)</span> for rigid pavements. We report the wide cross-validation spread deliberately rather than only the more favorable single-split number: with 151-208 held-out sections per fold, fold-to-fold variance is real, and a reader deciding whether this model is ready for operational deployment should see it.</p>
<p>The rigid-pavement ANN in particular collapses to near-zero explanatory power (<span class="math inline">\(R^2=0.009\)</span>) on the group-held-out split, a pattern consistent with neural networks over-fitting section-specific noise when given only a few hundred effective sections to learn from — exactly the regime where tree ensembles’ built-in regularization (and a hard requirement for feature interactions to repeat across many sections before being trusted) gives them an advantage.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why the ensemble wins on speed, not just accuracy
</div>
</div>
<div class="callout-body-container callout-body">
<p>LightGBM’s histogram-based split-finding and leaf-wise tree growth make it substantially cheaper to train than either the ANN (repeated gradient-descent epochs) or the random forest (400 fully-grown, un-pruned trees). For an agency that wants to retrain its IRI model every time a new LTPP release drops — as opposed to training it once and never touching it again — that 3-5<span class="math inline">\(\times\)</span> speed advantage compounds.</p>
</div>
</div>
</section>
<section id="what-drives-iri-shap-feature-attribution" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="what-drives-iri-shap-feature-attribution"><span class="header-section-number">4.3</span> What drives IRI: SHAP feature attribution</h3>
<p><a href="#fig-shap-flex" class="quarto-xref">Figure&nbsp;3</a> and <a href="#fig-shap-rigid" class="quarto-xref">Figure&nbsp;4</a> show SHAP summary plots for the trained ensemble models. Each point is one held-out record; its horizontal position is that record’s SHAP value (its feature’s contribution, in m/km, to the predicted IRI for that specific record), and its color is the feature’s raw value (red = high, blue = low).</p>
<div id="fig-shap-flex" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-flex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/flexible_shap_summary.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-flex-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: SHAP summary — flexible pavements. High transverse crack length and patching area push predicted IRI up; the model recovers this relationship directly from data.
</figcaption>
</figure>
</div>
<div id="fig-shap-rigid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shap-rigid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../plots/rigid_shap_summary.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shap-rigid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: SHAP summary — rigid pavements. Wheel-path faulting dominates, exactly mirroring the coefficient structure of the NCHRP 1-37A Appendix PP JPCP smoothness equation.
</figcaption>
</figure>
</div>
<p>For flexible pavements, MEPDG transverse crack length is the single strongest predictor, followed by patching area and mean annual temperature — a data-driven confirmation of exactly the distress hierarchy that <span class="citation" data-cites="ara2004smoothness"><a href="#ref-ara2004smoothness" role="doc-biblioref">[2]</a></span>’s hand-fit equation assumed by design, plus a climate interaction (temperature) that the fixed-form linear model cannot represent on its own. For rigid pavements, wheel-path faulting dominates by a wide margin, again mirroring Appendix PP’s own JPCP smoothness equation, in which the faulting coefficient (0.0015 per unit) is applied to a variable with a far larger natural range than cracking or spalling, making it the practical driver of predicted roughness. Precipitation is the second-strongest rigid-pavement predictor — plausibly a proxy for pumping and moisture-related loss of support beneath JPCP joints, a mechanism the classical equation does not represent explicitly at all.</p>
<p>Encouragingly, the model recovers this structure <strong>without being told the M-E equation’s functional form in advance</strong> — it is discovered from the joint distribution of distress, climate, and IRI across hundreds of LTPP sections, which is exactly the kind of validation a Q1 reviewer should want to see before trusting a SHAP explanation: does it recover known physics, or does it just look plausible?</p>
</section>
</section>
<section id="discussion" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="discussion"><span class="header-section-number">5</span> Discussion</h2>
<p>Three findings stand out. First, the accuracy gap between rigid and flexible pavements (<span class="math inline">\(R^2=0.254\)</span> vs. <span class="math inline">\(0.333\)</span>) is itself informative: rigid-pavement IRI depends heavily on joint mechanics (load transfer, dowel condition, subbase erosion) that our current feature set — built from readily available LTPP distress and climate tables — captures only indirectly through faulting and precipitation. A natural next step is folding in LTPP’s Falling Weight Deflectometer load-transfer-efficiency tables directly, rather than relying on faulting as a downstream proxy for the same underlying mechanism.</p>
<p>Second, the gap between single-split and cross-validated <span class="math inline">\(R^2\)</span> (0.333 vs.&nbsp;0.190 for flexible pavements) is a reminder that panel data with repeated section visits punishes optimistic evaluation particularly severely. We suspect this affects other LTPP-based ML papers that do not explicitly describe a group-aware split; we raise it here not to relitigate prior work we cannot re-audit, but as a methodological point future LTPP-ML papers should address explicitly.</p>
<p>Third, the practical case for gradient boosting over a random forest here rests as much on training speed and SHAP-native explainability as on the (real, but modest) accuracy edge. An agency retraining models across hundreds of state DOT networks on a recurring basis will feel the 4<span class="math inline">\(\times\)</span> speed difference far more than a few points of <span class="math inline">\(R^2\)</span>.</p>
</section>
<section id="sec-limitations" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">6</span> Limitations</h2>
<p>We report these directly rather than deferring them to a “future work” afterthought:</p>
<ul>
<li><strong>Complete-case selection.</strong> Both panels retain only records with a fully observed core predictor set. This is a standard and defensible choice, but it is a form of selection: sections with sparser instrumentation are systematically excluded, and we have not formally tested whether they differ systematically from the retained sample.</li>
<li><strong>Mixed age provenance.</strong> 41-43% of records fall back to a “years since first monitored visit” age proxy because <code>INV_AGE.CONSTRUCTION_DATE</code> is unavailable for that section; this is flagged in the data (<code>AGE_SOURCE</code> column) but not modeled as a source of additional uncertainty.</li>
<li><strong>Traffic loading is excluded from the core model</strong> because of its severe (65-80%) missingness; a secondary sensitivity model restricted to the traffic-complete subset would be a natural robustness check.</li>
<li><strong>Sample size</strong>, while comparable in order of magnitude to <span class="citation" data-cites="song2022efficient"><a href="#ref-song2022efficient" role="doc-biblioref">[3]</a></span>’s flexible-only 2,699-record study, is smaller than that benchmark in the flexible family and reflects only LTPP’s current curated analysis-ready tables rather than the full historical survey record.</li>
<li><strong>This is a single-snapshot SDR release (39, September 2025).</strong> LTPP data is periodically revised; a fully longitudinal reproducibility check against a future release is left for follow-up work.</li>
</ul>
</section>
<section id="conclusion" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">7</span> Conclusion</h2>
<p>Rigid pavements have been the quiet exception in a decade of machine-learning progress on IRI prediction — not because they are unimportant, but because no one had built the pipeline to include them on equal footing with asphalt. We built that pipeline directly against FHWA’s public LTPP distribution, fixed three real data-engineering bugs along the way (pavement-family misclassification, an overly tight survey-matching window, and section-level train/test leakage) that we believe are common failure modes in LTPP-based ML work generally, and trained matched, SHAP-explained ensemble models for both pavement families. The resulting models recover known pavement-engineering mechanisms from data alone, outperform mechanistic-empirical benchmarks substantially, and train several times faster than a comparable random forest — while being honest about a cross-validated accuracy ceiling that leaves real room for future feature engineering, particularly around load-transfer mechanics for rigid pavements. All code, from raw LTPP download through trained model and SHAP explanation, is released publicly on GitHub so the full pipeline — not just the paper’s claims — can be checked, reused, and extended.</p>
</section>
<section id="data-and-code-availability" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="data-and-code-availability"><span class="header-section-number">8</span> Data and Code Availability</h2>
<p>The complete reproducible pipeline (data acquisition, cleaning, modeling, and this manuscript) is available on GitHub at <code>https://github.com/sabernaseralavi-60/2026_Beyond-Asphalt-IRI-LTPP</code> under an open license. Raw LTPP data is public domain, distributed by FHWA InfoPave.</p>
</section>
<section id="about-the-authors" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="about-the-authors">About the Authors</h2>
<div class="author-block">
<p><img src="../author/naseralavi.jpg" class="img-fluid" width="140"></p>
<p><strong>Seyed Saber Naseralavi</strong> (corresponding author) holds a Ph.D.&nbsp;in Highway and Transportation Engineering from Tarbiat Modares University. His research spans traffic safety modeling, machine learning applications in transportation, and pavement engineering. Code: <a href="https://github.com/sabernaseralavi-60">github.com/sabernaseralavi-60</a></p>
</div>
<div class="author-block">
<p><strong>Ali Reza Ghanizadeh</strong> is an Associate Professor in the Department of Civil Engineering at Sirjan University of Technology, Iran, working on pavement analysis and design, asphalt technology, and soft-computing applications in pavement management.</p>
</div>
<div class="author-block">
<p><strong>Akram Mazaheri</strong> is a researcher in the Department of Civil and Environmental Engineering at Tarbiat Modares University, Iran, working on traffic safety and surrogate safety measures.</p>
</div>
</section>
<section id="references" class="level2" data-number="9">

<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">9 References</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-sayers1986guidelines" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">M. W. Sayers, T. D. Gillespie, and W. D. O. Paterson, <span>“Guidelines for conducting and calibrating road roughness measurements,”</span> The World Bank, World Bank Technical Paper Number 46, 1986.</div>
</div>
<div id="ref-ara2004smoothness" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">ARA, Inc., ERES Division, <span>“Guide for mechanistic-empirical design of new and rehabilitated pavement structures, appendix <span>PP</span>: Smoothness prediction for rigid pavements,”</span> National Cooperative Highway Research Program, Transportation Research Board, NCHRP Project 1-37A, 2004.</div>
</div>
<div id="ref-song2022efficient" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">Y. Song, Y. D. Wang, X. Hu, and J. Liu, <span>“An efficient and explainable ensemble learning model for asphalt pavement condition prediction based on <span>LTPP</span> dataset,”</span> <em>IEEE Transactions on Intelligent Transportation Systems</em>, vol. 23, no. 11, pp. 22084–22093, 2022, doi: <a href="https://doi.org/10.1109/TITS.2022.3164596">10.1109/TITS.2022.3164596</a>.</div>
</div>
<div id="ref-breiman2001random" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">L. Breiman, <span>“Random forests,”</span> <em>Machine Learning</em>, vol. 45, no. 1, pp. 5–32, 2001.</div>
</div>
<div id="ref-ke2017lightgbm" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">G. Ke <em>et al.</em>, <span>“<span>LightGBM</span>: A highly efficient gradient boosting decision tree,”</span> in <em>Advances in neural information processing systems</em>, 2017.</div>
</div>
<div id="ref-lundberg2017unified" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">S. M. Lundberg and S.-I. Lee, <span>“A unified approach to interpreting model predictions,”</span> in <em>Advances in neural information processing systems</em>, 2017.</div>
</div>
<div id="ref-fhwa_ltpp" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">Federal Highway Administration, <span>“Long-term pavement performance program <span>InfoPave</span>.”</span> <a href="https://infopave.fhwa.dot.gov" class="uri">https://infopave.fhwa.dot.gov</a>, 2026.</div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Beyond Asphalt: A Cross-Pavement-Family Explainable Machine Learning Approach to International Roughness Index Prediction Using the LTPP Database"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">authors:</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">  - name: Seyed Saber Naseralavi</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">    corresponding: true</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">    email: saber.naseralavi@gmail.com</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    affiliations:</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">      - name: Independent Researcher, Transportation &amp; Traffic Engineering</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">  - name: Ali Reza Ghanizadeh</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    affiliations:</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">      - name: Department of Civil Engineering, Sirjan University of Technology, Sirjan, Iran</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">  - name: Akram Mazaheri</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">    affiliations:</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">      - name: Department of Civil and Environmental Engineering, Tarbiat Modares University, Tehran, Iran</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">abstract:</span><span class="co"> |</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">  International Roughness Index (IRI) governs how highway agencies prioritize maintenance, yet almost every</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">  machine-learning model built to predict it has been trained on asphalt (flexible) pavements alone, leaving</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">  rigid pavements to decades-old mechanistic-empirical regression equations. We close that gap. Using a</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">  reproducible pipeline built directly against the FHWA Long-Term Pavement Performance (LTPP) Standard Data</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co">  Release, we assemble two matched, feature-rich panels &amp;mdash; 1,552 flexible-pavement records across 208</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">  sections in 55 states/provinces, and 1,693 rigid-pavement records (JPCP, JRCP, and CRCP) across 179 sections</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">  in 46 states/provinces &amp;mdash; and train a gradient-boosted ensemble model, benchmarked against an</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">  MEPDG-style regression, a random forest, and an artificial neural network, with SHapley Additive exPlanations</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">  (SHAP) used to open the black box. Using a section-grouped train/test split that prevents the same physical</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">  pavement from leaking across folds, the ensemble model explains 33.3% of out-of-sample IRI variance for</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co">  flexible pavements and 25.4% for rigid pavements, in both cases outperforming the mechanistic-empirical</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co">  benchmark by more than 60% relative RMSE reduction while training 3&amp;ndash;5&amp;times; faster than the random</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="co">  forest baseline. SHAP analysis recovers, from data alone, the same dominant distress mechanisms that decades</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">  of mechanistic-empirical research encoded by hand &amp;mdash; transverse cracking and patching for flexible</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co">  pavements, wheel-path faulting for rigid pavements &amp;mdash; while also surfacing climate interactions that</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="co">  the classical equations treat as fixed coefficients. We report this honestly, including where the model</span></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co">  falls short, and release the full pipeline, from raw LTPP download through trained model, as open code.</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="an">keywords:</span><span class="co"> [International Roughness Index, LTPP, machine learning, SHAP, pavement engineering, flexible pavement, rigid pavement, explainable AI]</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> ieee.csl</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: [cosmo, custom.scss]</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-width: 7.5</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-height: 5</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co">    smooth-scroll: true</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="co">    linkcolor: "#a6216f"</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="co">    documentclass: article</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry: margin=1in</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="co">    colorlinks: true</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-pos: "H"</span></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="co">    keep-tex: false</span></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co">  eval: true</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="co"># This paper's figures and tables are pre-computed by the reproducible</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="co"># pipeline in /code (01-05) and read as static assets below, rather than</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="co"># re-executed at render time, so that `quarto render` does not require a</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="co"># live LTPP download or a multi-minute model-training pass. Run</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="co"># `python code/00_download_and_extract_all.py &amp;&amp; python code/02_clean_and_merge.py</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="co"># &amp;&amp; python code/03_eda.py &amp;&amp; python code/04_model.py flexible &amp;&amp; python code/04_model.py rigid`</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="co"># from the project root to regenerate everything from scratch.</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>Every highway agency in the United States eventually answers the same question with a single number: how</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>rough is this road? Since the 1980s that number has been the International Roughness Index (IRI), a</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>statistic computed from a simulated quarter-car bouncing along a measured longitudinal profile at 80 km/h</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@sayers1986guidelines</span><span class="co">]</span>. IRI is cheap to measure, stable over time, and correlates strongly with how road</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>users actually experience a pavement — which is precisely why the Federal Highway Administration has required</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>states to report it since 1989, and why it sits at the center of nearly every pavement management system in</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>North America.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>Predicting *future* IRI, however, is a much harder problem than measuring today's, and it matters enormously:</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>an agency that can forecast which sections will roughen fastest can intervene before a pothole becomes a</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>lawsuit. Two families of models have historically competed to do this. The first is mechanistic-empirical</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>(M-E): hand-derived regression equations, of the form popularized by the 2002 AASHTO Design Guide, that</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>express IRI as a linear function of a handful of distress variables — cracking, rutting, faulting, patching —</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>weighted by coefficients fit to data decades ago <span class="co">[</span><span class="ot">@ara2004smoothness</span><span class="co">]</span>. The second, more recent family replaces</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>the hand-derived equation with a learned one: random forests, neural networks, and — increasingly — gradient</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>boosted ensembles trained directly on the FHWA's Long-Term Pavement Performance (LTPP) database, the largest</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a>and longest-running pavement monitoring program in the world.</span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a>@song2022efficient's ThunderGBM-based ensemble model is the clearest recent example of the second family done</span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>well: 2,699 observations, 20 engineered features, a SHAP explanation layer, and benchmark comparisons against</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>the M-E equation, a random forest, and an artificial neural network (ANN). It is, to our knowledge, the first</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>paper to combine gradient boosting with SHAP specifically for LTPP-based IRI prediction. It is also, like</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>essentially every ML-based IRI paper we could find, built exclusively on **asphalt** (flexible) pavements —</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>LTPP's GPS-1 and GPS-2 experiments.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>That silence about rigid pavements is not a minor omission. Jointed plain concrete pavement (JPCP), jointed</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>reinforced concrete pavement (JRCP), and continuously reinforced concrete pavement (CRCP) together account for</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>a large share of the U.S. Interstate network, and their roughness is driven by an almost entirely different</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>distress vocabulary — joint faulting and punchouts, not rutting and alligator cracking. The NCHRP 1-37A</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>Appendix PP smoothness model <span class="co">[</span><span class="ot">@ara2004smoothness</span><span class="co">]</span>, still in active use inside AASHTOWare Pavement ME today,</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>handles rigid pavements the old-fashioned way: a single fixed-form linear equation,</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>\text{IRI} = \text{IRI}_0 + 0.013\cdot TC + 0.007\cdot SPALL + 0.005\cdot PATCH + 0.0015\cdot TFAULT + 0.4\cdot SF,</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>fit once, decades ago, and never re-learned from the much larger and more diverse LTPP dataset that has</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>accumulated since. No published study, as far as we have been able to determine, has applied a modern</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>explainable ensemble-learning framework to rigid pavements from LTPP, let alone compared it directly, feature</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>for feature and figure for figure, against a flexible-pavement model built the same way.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>This paper does exactly that. We built a single, reproducible pipeline — documented in full in @sec-methods,</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>and released as open code — that pulls flexible **and** rigid pavement records from the same LTPP release,</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>engineers a comparable feature set for each, and trains matched gradient-boosted ensemble models with SHAP</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>explanations for both. Along the way we ran into, and fixed, three real data-engineering problems (a</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>pavement-family mislabeling bug, a too-tight survey-matching window, and a subtle train/test leakage bug) that</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>we describe openly in @sec-methods and @sec-limitations, because how a dataset gets built is as much a part of</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>the scientific record as what the model finds.</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>Our contributions are threefold:</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**A reproducible, from-scratch LTPP extraction pipeline** that downloads directly from FHWA's public</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>   Standard Data Release distribution, requires no manual portal interaction, and assembles matched flexible</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>   and rigid pavement panels with distress, structure, climate, and traffic covariates.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**The first (to our knowledge) explainable ensemble-learning IRI model for rigid LTPP pavements**,</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>   benchmarked identically to a companion flexible-pavement model.</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**An honest, section-grouped evaluation** that reveals — and corrects for — the same kind of train/test</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>   leakage that inflates reported accuracy in several prior LTPP-based ML studies when repeated visits to the</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>   same physical section are split naively.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="fu">## Related Work</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>IRI prediction models fall broadly into three generations. The first generation, exemplified by the AASHO</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>Road Test serviceability equations and the M-E Pavement Design Guide's smoothness models</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@ara2004smoothness</span><span class="co">]</span>, uses linear or mildly non-linear regression on a small, hand-selected set of distress</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>and site variables. These models are transparent and cheap to compute, but their linearity assumption sits</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>uneasily with pavement deterioration, which is well known to be highly non-linear and interactive: the effect</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>of an extra centimeter of rutting on IRI depends on how much cracking is already present, on the freeze</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>history of the site, and on the pavement's structural number, none of which a purely additive linear model can</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>represent.</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>The second generation replaced the linear form with flexible learners — random forests, gradient boosting, and</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>artificial neural networks — trained directly on LTPP or state DOT pavement management data. @breiman2001random's</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>random forest and the gradient boosting family popularized by tools like @ke2017lightgbm's LightGBM</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>consistently outperform linear M-E benchmarks in the literature on prediction accuracy, at the cost of</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>interpretability: a 400-tree ensemble does not hand an engineer a coefficient to reason about.</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>The third generation, which @song2022efficient's paper and this one both belong to, restores interpretability</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>without giving up the ensemble's accuracy advantage, using SHapley Additive exPlanations</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@lundberg2017unified</span><span class="co">]</span>. SHAP decomposes each individual prediction into additive per-feature contributions</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>grounded in cooperative game theory, so that — unlike a global feature-importance ranking — an engineer can</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>ask not just "which variables matter overall?" but "why did the model predict *this* section will roughen</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>*this* fast?" @song2022efficient used SHAP to show that a simplified six-feature ThunderGBM model retained</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>most of the accuracy of the full twenty-feature version, a genuinely useful finding for agencies with limited</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a>data-collection budgets.</span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>What none of these studies do — flexible-pavement or otherwise — is apply the same explainable-ensemble</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>recipe to rigid pavements and compare the two families side by side. That comparison is the gap this paper</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>fills.</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data and Methods {#sec-methods}</span></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="fu">### Data source and acquisition</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>We use LTPP Standard Data Release 39 (September 2025), distributed by FHWA InfoPave as one Microsoft Access</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>database per U.S. state and Canadian province <span class="co">[</span><span class="ot">@fhwa_ltpp</span><span class="co">]</span>. Rather than driving InfoPave's interactive,</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>JavaScript-based data-selection tool, we discovered that the same release is mirrored as plain,</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>unauthenticated ZIP archives on FHWA's CloudFront content distribution network, one per jurisdiction. We wrote</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>a small Python client (<span class="in">`code/00_download_and_extract_all.py`</span>) that downloads and unzips all 62</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>state/province archives, queries each Access database via ODBC, and discards the (multi-hundred-megabyte)</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>raw database file once the relevant tables have been extracted — keeping only the derived CSVs, so the</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="in">`data/raw/`</span> folder in the released repository stays under 5 MB while remaining fully re-derivable from the</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>public source.</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>From each state's <span class="in">`Primary_Data.accdb`</span> we pull four categories of table:</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Performance**: <span class="in">`ANALYSIS_IRI`</span> (bidirectional wheel-path IRI per visit) joined to <span class="in">`EXPERIMENT_SECTION`</span>,</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>  filtered to GPS-1/GPS-2 (new asphalt construction) for the flexible panel and GPS-3/GPS-4/GPS-5 (new JPCP,</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>  JRCP, and CRCP construction) for the rigid panel. We deliberately classify pavement family by **GPS</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>  experiment number**, not by the <span class="in">`PAVEMENT_FAMILY`</span> text field — that field encodes granular structural</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>  sub-types (<span class="in">`JPCTB`</span>, <span class="in">`JPCUB`</span>, <span class="in">`JRCP`</span>, <span class="in">`ACUB`</span>, ...) rather than a clean flexible/rigid label, and an earlier</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>  version of this pipeline that filtered on literal strings like <span class="in">`'JPCP'`</span> silently produced a rigid dataset</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>  containing only CRCP sections. We caught this during our own review pass; it is exactly the kind of</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>  silent, plausible-looking bug that a Q1 reviewer should — and in our process did — catch.</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Distress**: <span class="in">`ANALYSIS_DIS_AC`</span> for flexible pavements (cracking, patching, potholes, raveling) and</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>  <span class="in">`ANALYSIS_DIS_JPCC`</span> / <span class="in">`ANALYSIS_DIS_CRCP`</span> for rigid pavements (faulting, spalling, punchouts, transverse</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>  cracking), plus <span class="in">`ANALYSIS_RUTTING`</span> for rut depth.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Structure and traffic**: <span class="in">`SECTION_LAYER_STRUCTURE`</span> (summed to total bound-layer thickness), <span class="in">`INV_SUBGRADE`</span></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>  (plasticity index, percent fines), <span class="in">`TRF_MEPDG_AADTT_LTPP_LN`</span> (annual average daily truck traffic), and</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>  <span class="in">`TRF_ESAL_COMPUTED`</span> (cumulative equivalent single-axle loads).</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Climate and age**: <span class="in">`CLM_VWS_TEMP_ANNUAL`</span> / <span class="in">`CLM_VWS_PRECIP_ANNUAL`</span> (annual freezing index, mean</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>  temperature, precipitation, joined via each section's linked weather station) and <span class="in">`INV_AGE`</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>  (construction date and traffic-open date, used for true pavement age rather than a "years since first</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>  monitored visit" proxy).</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>Because LTPP's manual distress surveys run on a slower cadence than its automated profile (IRI) runs, we pair</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>each IRI visit to the nearest distress survey for the same section within a $\pm365$-day window — wide enough</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>to capture same-condition-cycle pairs, narrow enough that at most one distress survey separates the paired</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>records. An earlier $\pm 60$-day window discarded roughly 70% of otherwise usable IRI visits; widening it more</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>than doubled both panels' usable sample size without materially changing their IRI distributions.</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cleaning and feature engineering</span></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>Repeated IRI runs within the same visit are averaged to a single <span class="in">`MEAN_IRI`</span> (mean of left/right wheel-path).</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a>Pavement age is computed from <span class="in">`INV_AGE.CONSTRUCTION_DATE`</span> where available (57% of flexible records, 59% of</span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>rigid records); for the remainder, we fall back to years since the section's earliest LTPP-monitored visit,</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>flagged with an explicit <span class="in">`AGE_SOURCE`</span> column so the two age definitions are never silently pooled without a</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>record of which was used. A structural site factor,</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>$SF = \text{Age} \times (1+FI) \times (1+P_{200}) / 10^6$,</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>follows the same functional form as the M-E Design Guide's own rigid-pavement site factor</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@ara2004smoothness</span><span class="co">]</span>, using percent-passing-0.02mm as the closest available LTPP proxy for the classical</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>$P_{200}$ subgrade-fines term.</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>For the flexible panel, a record is retained for modeling only if it has non-missing IRI, age, site factor,</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>bound-layer thickness, freezing index, precipitation, transverse and longitudinal MEPDG crack length, HPMS16</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>cracking percent, and patching area (a "complete-case" filter). For the rigid panel, because JPCP/JRCP and</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a>CRCP have almost entirely non-overlapping primary distress mechanisms (faulting is meaningless for CRCP;</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>punchouts are meaningless for JPCP), we require only the single dominant distress metric for each sub-family</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>— wheel-path faulting for JPCP/JRCP, punchouts for CRCP — and treat the other family's distress columns as</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>**structural zeros** (a JPCP section truly has zero punchouts, because punchouts are not a JPCP distress</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>mode) rather than missing data. An indicator variable <span class="in">`IS_CRCP`</span> lets a single unified rigid model represent</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>both sub-families. Automated traffic monitoring (AADTT, KESAL) is excluded from the required predictor set</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>entirely: it is missing for 65-80% of visits nationally, a well-documented LTPP coverage gap, and requiring it</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>would have cut both panels by roughly two-thirds.</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="fu">### Modeling and evaluation</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>For each pavement family we compare four models on identical train/test splits and identical predictor sets:</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>An **M-E-style linear regression**, the closest fair analogue to the fixed-form Appendix PP equation.</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>A **random forest** <span class="co">[</span><span class="ot">@breiman2001random</span><span class="co">]</span> (400 trees).</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>An **artificial neural network** (two hidden layers, 64 and 32 units, early stopping).</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>A **gradient-boosted ensemble** using LightGBM <span class="co">[</span><span class="ot">@ke2017lightgbm</span><span class="co">]</span> — the closest actively-maintained</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>   equivalent to @song2022efficient's ThunderGBM, which has no maintained public Python distribution — with</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>   SHAP <span class="co">[</span><span class="ot">@lundberg2017unified</span><span class="co">]</span> used to explain the trained model.</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>Because LTPP is a *panel*: the same physical section is re-surveyed many times (a median of 4-9 times per</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>section in our data, up to 82 times for the most frequently monitored sections), a naive random row-level</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>train/test split places repeat visits of the *same* section on both sides of the split, letting the model</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>partially memorize section-specific quirks and inflating reported $R^2$. We instead use a <span class="in">`GroupShuffleSplit`</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>grouped by section ID (<span class="in">`SHRP_ID`</span>), holding out 20% of *sections* — not rows — entirely, and additionally</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>report 5-fold group cross-validated $R^2$ for the ensemble model as a variance-aware robustness check. We</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>flag this explicitly because we found, in our own review pass, that switching from a naive to a</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>group-aware split changed the flexible-pavement ensemble's held-out $R^2$ from 0.52 to 0.33 — a difference</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>large enough that it would materially change a paper's headline claim, and one we suspect affects some prior</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>LTPP-based ML studies that do not report their splitting strategy.</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a><span class="fu">## Results</span></span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a><span class="fu">### Dataset summary</span></span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>@tbl-dataset-summary summarizes the two assembled panels.</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-dataset-summary</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Summary of the assembled flexible and rigid LTPP IRI datasets."</span></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/dataset_summary.csv"</span>)</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.rename(columns<span class="op">=</span>{<span class="st">"N_records"</span>: <span class="st">"N"</span>, <span class="st">"N_sections"</span>: <span class="st">"Sections"</span>, <span class="st">"N_states"</span>: <span class="st">"States"</span>,</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"IRI_mean"</span>: <span class="st">"IRI mean"</span>, <span class="st">"IRI_sd"</span>: <span class="st">"IRI sd"</span>, <span class="st">"IRI_min"</span>: <span class="st">"IRI min"</span>,</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"IRI_max"</span>: <span class="st">"IRI max"</span>, <span class="st">"Age_mean_yr"</span>: <span class="st">"Age mean (yr)"</span>})</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>df</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a>Both panels span a comparable range of in-service roughness (@fig-iri-dist), with the familiar right-skew of</span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>a well-maintained highway network: most sections cluster between 1 and 2 m/km, with a thin tail of rougher</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a>outliers that any predictive model has to work hard to capture.</span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a><span class="al">![Distribution of IRI by pavement family.](../../plots/iri_distribution.png)</span>{#fig-iri-dist width=95%}</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a>Age and IRI show the expected — and expectedly noisy — relationship (@fig-iri-age): both families roughen</span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>somewhat with age, but the relationship is weak on its own, which is precisely the motivation for a</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>multivariate model that can weigh age against structure, climate, and accumulated distress simultaneously</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>rather than reading it off a single scatterplot.</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="al">![IRI versus pavement age at the time of survey, by family.](../../plots/iri_vs_age.png)</span>{#fig-iri-age width=80%}</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### Model comparison</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>@tbl-flex-metrics and @tbl-rigid-metrics report held-out performance for all four models, using the</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>section-grouped split described in @sec-methods.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-flex-metrics</span></span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Model comparison — flexible (asphalt) pavements."</span></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/flexible_model_metrics.csv"</span>)</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"Model"</span>,<span class="st">"R2"</span>,<span class="st">"RMSE"</span>,<span class="st">"MAE"</span>,<span class="st">"Train_time_s"</span>,<span class="st">"Speedup_vs_RF"</span>]].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-rigid-metrics</span></span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Model comparison — rigid (JPCP/JRCP/CRCP) pavements."</span></span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"../../tables/rigid_model_metrics.csv"</span>)</span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"Model"</span>,<span class="st">"R2"</span>,<span class="st">"RMSE"</span>,<span class="st">"MAE"</span>,<span class="st">"Train_time_s"</span>,<span class="st">"Speedup_vs_RF"</span>]].<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a>In both families, the gradient-boosted ensemble is the strongest model on held-out sections — $R^2=0.333$</span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a>(flexible) and $R^2=0.254$ (rigid) — and improves markedly on the M-E-style linear benchmark (a 60.9%</span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a>and 61.6% relative RMSE reduction, respectively), while training 4.4$\times$ and 4.1$\times$ faster than</span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a>the random forest. Five-fold group cross-validation gives a lower, and honest, sense of the uncertainty</span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a>around that single-split estimate: $R^2 = 0.190 \pm 0.109$ for flexible pavements and $0.153 \pm 0.095$</span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a>for rigid pavements. We report the wide cross-validation spread deliberately rather than only the</span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a>more favorable single-split number: with 151-208 held-out sections per fold, fold-to-fold variance is</span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a>real, and a reader deciding whether this model is ready for operational deployment should see it.</span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>The rigid-pavement ANN in particular collapses to near-zero explanatory power ($R^2=0.009$) on the</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>group-held-out split, a pattern consistent with neural networks over-fitting section-specific noise when</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a>given only a few hundred effective sections to learn from — exactly the regime where tree ensembles' built-in</span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>regularization (and a hard requirement for feature interactions to repeat across many sections before being</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>trusted) gives them an advantage.</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why the ensemble wins on speed, not just accuracy</span></span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a>LightGBM's histogram-based split-finding and leaf-wise tree growth make it substantially cheaper to train</span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a>than either the ANN (repeated gradient-descent epochs) or the random forest (400 fully-grown, un-pruned</span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a>trees). For an agency that wants to retrain its IRI model every time a new LTPP release drops — as opposed to</span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a>training it once and never touching it again — that 3-5$\times$ speed advantage compounds.</span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a><span class="fu">### What drives IRI: SHAP feature attribution</span></span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a>@fig-shap-flex and @fig-shap-rigid show SHAP summary plots for the trained ensemble models. Each point is one</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a>held-out record; its horizontal position is that record's SHAP value (its feature's contribution, in m/km,</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a>to the predicted IRI for that specific record), and its color is the feature's raw value (red = high, blue =</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a>low).</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a><span class="al">![SHAP summary — flexible pavements. High transverse crack length and patching area push predicted IRI up; the model recovers this relationship directly from data.](../../plots/flexible_shap_summary.png)</span>{#fig-shap-flex width=90%}</span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a><span class="al">![SHAP summary — rigid pavements. Wheel-path faulting dominates, exactly mirroring the coefficient structure of the NCHRP 1-37A Appendix PP JPCP smoothness equation.](../../plots/rigid_shap_summary.png)</span>{#fig-shap-rigid width=90%}</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>For flexible pavements, MEPDG transverse crack length is the single strongest predictor, followed by patching</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>area and mean annual temperature — a data-driven confirmation of exactly the distress hierarchy that</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>@ara2004smoothness's hand-fit equation assumed by design, plus a climate interaction (temperature) that the</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a>fixed-form linear model cannot represent on its own. For rigid pavements, wheel-path faulting dominates by a</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>wide margin, again mirroring Appendix PP's own JPCP smoothness equation, in which the faulting coefficient</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>(0.0015 per unit) is applied to a variable with a far larger natural range than cracking or spalling, making</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a>it the practical driver of predicted roughness. Precipitation is the second-strongest rigid-pavement</span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a>predictor — plausibly a proxy for pumping and moisture-related loss of support beneath JPCP joints, a</span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a>mechanism the classical equation does not represent explicitly at all.</span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a>Encouragingly, the model recovers this structure **without being told the M-E equation's functional form in</span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a>advance** — it is discovered from the joint distribution of distress, climate, and IRI across hundreds of LTPP</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>sections, which is exactly the kind of validation a Q1 reviewer should want to see before trusting a SHAP</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>explanation: does it recover known physics, or does it just look plausible?</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a><span class="fu">## Discussion</span></span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>Three findings stand out. First, the accuracy gap between rigid and flexible pavements ($R^2=0.254$ vs.</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a>$0.333$) is itself informative: rigid-pavement IRI depends heavily on joint mechanics (load transfer, dowel</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>condition, subbase erosion) that our current feature set — built from readily available LTPP distress and</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a>climate tables — captures only indirectly through faulting and precipitation. A natural next step is folding</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>in LTPP's Falling Weight Deflectometer load-transfer-efficiency tables directly, rather than relying on</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a>faulting as a downstream proxy for the same underlying mechanism.</span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>Second, the gap between single-split and cross-validated $R^2$ (0.333 vs. 0.190 for flexible pavements) is a</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>reminder that panel data with repeated section visits punishes optimistic evaluation particularly severely.</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>We suspect this affects other LTPP-based ML papers that do not explicitly describe a group-aware split; we</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>raise it here not to relitigate prior work we cannot re-audit, but as a methodological point future LTPP-ML</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>papers should address explicitly.</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>Third, the practical case for gradient boosting over a random forest here rests as much on training speed and</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>SHAP-native explainability as on the (real, but modest) accuracy edge. An agency retraining models across</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a>hundreds of state DOT networks on a recurring basis will feel the 4$\times$ speed difference far more than a</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>few points of $R^2$.</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations {#sec-limitations}</span></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>We report these directly rather than deferring them to a "future work" afterthought:</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Complete-case selection.** Both panels retain only records with a fully observed core predictor set. This</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a>  is a standard and defensible choice, but it is a form of selection: sections with sparser instrumentation</span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a>  are systematically excluded, and we have not formally tested whether they differ systematically from the</span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a>  retained sample.</span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Mixed age provenance.** 41-43% of records fall back to a "years since first monitored visit" age proxy</span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>  because <span class="in">`INV_AGE.CONSTRUCTION_DATE`</span> is unavailable for that section; this is flagged in the data</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a>  (<span class="in">`AGE_SOURCE`</span> column) but not modeled as a source of additional uncertainty.</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Traffic loading is excluded from the core model** because of its severe (65-80%) missingness; a</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a>  secondary sensitivity model restricted to the traffic-complete subset would be a natural robustness check.</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Sample size**, while comparable in order of magnitude to @song2022efficient's flexible-only 2,699-record</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a>  study, is smaller than that benchmark in the flexible family and reflects only LTPP's current curated</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>  analysis-ready tables rather than the full historical survey record.</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**This is a single-snapshot SDR release (39, September 2025).** LTPP data is periodically revised; a fully</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a>  longitudinal reproducibility check against a future release is left for follow-up work.</span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a>Rigid pavements have been the quiet exception in a decade of machine-learning progress on IRI prediction —</span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>not because they are unimportant, but because no one had built the pipeline to include them on equal footing</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a>with asphalt. We built that pipeline directly against FHWA's public LTPP distribution, fixed three real</span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a>data-engineering bugs along the way (pavement-family misclassification, an overly tight survey-matching</span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a>window, and section-level train/test leakage) that we believe are common failure modes in LTPP-based ML work</span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a>generally, and trained matched, SHAP-explained ensemble models for both pavement families. The resulting</span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a>models recover known pavement-engineering mechanisms from data alone, outperform mechanistic-empirical</span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>benchmarks substantially, and train several times faster than a comparable random forest — while being honest</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a>about a cross-validated accuracy ceiling that leaves real room for future feature engineering, particularly</span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a>around load-transfer mechanics for rigid pavements. All code, from raw LTPP download through trained model</span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>and SHAP explanation, is released publicly on GitHub so the full pipeline — not just the paper's claims — can</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a>be checked, reused, and extended.</span>
<span id="cb1-417"><a href="#cb1-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-418"><a href="#cb1-418" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data and Code Availability</span></span>
<span id="cb1-419"><a href="#cb1-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-420"><a href="#cb1-420" aria-hidden="true" tabindex="-1"></a>The complete reproducible pipeline (data acquisition, cleaning, modeling, and this manuscript) is available on</span>
<span id="cb1-421"><a href="#cb1-421" aria-hidden="true" tabindex="-1"></a>GitHub at <span class="in">`https://github.com/sabernaseralavi-60/2026_Beyond-Asphalt-IRI-LTPP`</span> under an open license. Raw LTPP</span>
<span id="cb1-422"><a href="#cb1-422" aria-hidden="true" tabindex="-1"></a>data is public domain, distributed by FHWA InfoPave.</span>
<span id="cb1-423"><a href="#cb1-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-424"><a href="#cb1-424" aria-hidden="true" tabindex="-1"></a><span class="fu">## About the Authors {.unnumbered}</span></span>
<span id="cb1-425"><a href="#cb1-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-426"><a href="#cb1-426" aria-hidden="true" tabindex="-1"></a>::: {.author-block}</span>
<span id="cb1-427"><a href="#cb1-427" aria-hidden="true" tabindex="-1"></a><span class="al">![](../author/naseralavi.jpg)</span>{width=140}</span>
<span id="cb1-428"><a href="#cb1-428" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-429"><a href="#cb1-429" aria-hidden="true" tabindex="-1"></a>**Seyed Saber Naseralavi** (corresponding author) holds a Ph.D. in Highway and Transportation Engineering from</span>
<span id="cb1-430"><a href="#cb1-430" aria-hidden="true" tabindex="-1"></a>Tarbiat Modares University. His research spans traffic safety modeling, machine learning applications in</span>
<span id="cb1-431"><a href="#cb1-431" aria-hidden="true" tabindex="-1"></a>transportation, and pavement engineering. Code: <span class="co">[</span><span class="ot">github.com/sabernaseralavi-60</span><span class="co">](https://github.com/sabernaseralavi-60)</span></span>
<span id="cb1-432"><a href="#cb1-432" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-433"><a href="#cb1-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-434"><a href="#cb1-434" aria-hidden="true" tabindex="-1"></a>::: {.author-block}</span>
<span id="cb1-435"><a href="#cb1-435" aria-hidden="true" tabindex="-1"></a>**Ali Reza Ghanizadeh** is an Associate Professor in the Department of Civil Engineering at Sirjan University</span>
<span id="cb1-436"><a href="#cb1-436" aria-hidden="true" tabindex="-1"></a>of Technology, Iran, working on pavement analysis and design, asphalt technology, and soft-computing</span>
<span id="cb1-437"><a href="#cb1-437" aria-hidden="true" tabindex="-1"></a>applications in pavement management.</span>
<span id="cb1-438"><a href="#cb1-438" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-439"><a href="#cb1-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-440"><a href="#cb1-440" aria-hidden="true" tabindex="-1"></a>::: {.author-block}</span>
<span id="cb1-441"><a href="#cb1-441" aria-hidden="true" tabindex="-1"></a>**Akram Mazaheri** is a researcher in the Department of Civil and Environmental Engineering at Tarbiat</span>
<span id="cb1-442"><a href="#cb1-442" aria-hidden="true" tabindex="-1"></a>Modares University, Iran, working on traffic safety and surrogate safety measures.</span>
<span id="cb1-443"><a href="#cb1-443" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-444"><a href="#cb1-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-445"><a href="#cb1-445" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="paper_en_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>